/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 14 08:56:50 GMT 2016
 */

package org.openecomp.mso.openstack.beans;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class MsoTenantESTest extends MsoTenantESTestscaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MsoTenant msoTenant0 = new MsoTenant("P<5j-:=G4zf", "P<5j-:=G4zf", (Map<String, String>) null);
      String string0 = msoTenant0.getTenantName();
      assertEquals("P<5j-:=G4zf", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MsoTenant msoTenant0 = new MsoTenant("", "", (Map<String, String>) null);
      String string0 = msoTenant0.getTenantName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MsoTenant msoTenant0 = new MsoTenant();
      String string0 = msoTenant0.getTenantName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MsoTenant msoTenant0 = new MsoTenant();
      Map<String, String> map0 = msoTenant0.getMetadata();
      assertNull(map0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MsoTenant msoTenant0 = new MsoTenant("", "SsK{%:", (Map<String, String>) null);
      String string0 = msoTenant0.getTenantId();
      assertEquals("", string0);
      assertEquals("SsK{%:", msoTenant0.getTenantName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MsoTenant msoTenant0 = new MsoTenant();
      msoTenant0.setTenantId("9A");
      String string0 = msoTenant0.getTenantId();
      assertEquals("9A", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MsoTenant msoTenant0 = new MsoTenant();
      msoTenant0.setMetadata((Map<String, String>) null);
      assertNull(msoTenant0.getTenantName());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MsoTenant msoTenant0 = new MsoTenant();
      msoTenant0.setTenantName("9A");
      assertNull(msoTenant0.getTenantId());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MsoTenant msoTenant0 = new MsoTenant();
      String string0 = msoTenant0.getTenantId();
      assertNull(string0);
  }
}
