/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 14 13:48:50 GMT 2016
 */

package org.openecomp.camunda.bpmn.plugin.urnmap.db;

import org.junit.Test;

import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.openecomp.camunda.bpmn.plugin.urnmap.db.URNData;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class URNDataESTest extends URNDataESTestscaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      URNData uRNData0 = new URNData();
      uRNData0.setVer_("yE)");
      String string0 = uRNData0.getVer_();
      assertEquals("yE)", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      URNData uRNData0 = new URNData();
      uRNData0.setURNValue("Dw]M@,~.D");
      String string0 = uRNData0.getURNValue();
      assertEquals("Dw]M@,~.D", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      URNData uRNData0 = new URNData();
      uRNData0.setURNName("");
      String string0 = uRNData0.getURNName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      URNData uRNData0 = new URNData();
      String string0 = uRNData0.getVer_();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      URNData uRNData0 = new URNData();
      String string0 = uRNData0.getURNValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      URNData uRNData0 = new URNData();
      String string0 = uRNData0.getURNName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      URNData uRNData0 = new URNData();
      uRNData0.setURNValue("");
      String string0 = uRNData0.getURNValue();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      URNData uRNData0 = new URNData();
      uRNData0.setVer_("");
      String string0 = uRNData0.getVer_();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      URNData uRNData0 = new URNData();
      uRNData0.setURNName("2Gv9h[mmV=,z\"VSY`t)");
      String string0 = uRNData0.getURNName();
      assertEquals("2Gv9h[mmV=,z\"VSY`t)", string0);
  }
}
