use catalogdb;

INSERT INTO rainy_day_handler_macro (FLOW_NAME, SERVICE_TYPE, VNF_TYPE, ERROR_CODE, WORK_STEP, POLICY)
VALUES
('ActivateNetworkBB', '*', '*', '*', "*" , 'Rollback'),
('ActivateNetworkCollectionBB', '*', '*', '*', "*" , 'Rollback'),
('ActivateServiceInstanceBB', '*', '*', '*', "*" , 'Rollback'),
('ActivateVfModuleBB', '*', '*', '*', "*" , 'Rollback'),
('ActivateVnfBB', '*', '*', '*', "*" , 'Rollback'),
('ActivateVolumeGroupBB', '*', '*', '*', "*" , 'Rollback'),
('AssignNetwork1802BB', '*', '*', '*', "*" , 'Rollback'),
('AssignNetworkBB', '*', '*', '*', "*" , 'Rollback'),
('AssignServiceInstanceBB', '*', '*', '*', "*" , 'Rollback'),
('AssignVfModuleBB', '*', '*', '*', "*" , 'Rollback'),
('AssignVnfBB', '*', '*', '*', "*" , 'Rollback'),
('AssignVolumeGroupBB', '*', '*', '*', "*" , 'Rollback'),
('CreateNetworkBB', '*', '*', '*', "*" , 'Retry'),
('CreateNetworkCollectionBB', '*', '*', '*', "*" , 'Retry'),
('CreateVfModuleBB', '*', '*', '*', "*" , 'Retry'),
('CreateVolumeGroupBB', '*', '*', '*', "*" , 'Retry'),
('ChangeModelServiceInstanceBB', '*', '*', '*', "*" , 'Abort'),
('ChangeModelVfModuleBB', '*', '*', '*', "*" , 'Abort'),
('ChangeModelVnfBB', '*', '*', '*', "*" , 'Abort'),
('CreateCustomerBB', '*', '*', '*', "*" , 'Abort'),
('DeactivateNetworkBB', '*', '*', '*', "*" , 'Abort'),
('DeactivateServiceInstanceBB', '*', '*', '*', "*" , 'Abort'),
('DeactivateVfModuleBB', '*', '*', '*', "*" , 'Abort'),
('DeactivateVnfBB', '*', '*', '*', "*" , 'Abort'),
('DeactivateVolumeGroupBB', '*', '*', '*', "*" , 'Abort'),
('DeleteNetworkBB', '*', '*', '*', "*" , 'Retry'),
('DeleteNetworkCollectionBB', '*', '*', '*', "*" , 'Retry'),
('DeleteVfModuleBB', '*', '*', '*', "*" , 'Retry'),
('DeleteVolumeGroupBB', '*', '*', '*', "*" , 'Retry'),
('UnassignNetwork1802BB', '*', '*', '*', "*" , 'Retry'),
('UnassignNetworkBB', '*', '*', '*', "*" , 'Retry'),
('UnassignServiceInstanceBB', '*', '*', '*', "*" , 'Retry'),
('UnassignVfModuleBB', '*', '*', '*', "*" , 'Retry'),
('UnassignVnfBB', '*', '*', '*', "*" , 'Retry'),
('UnassignVolumeGroupBB', '*', '*', '*', "*" , 'Retry'),
('UpdateNetworkBB', '*', '*', '*', "*" , 'Retry'),
('VnfAdapterBB', '*', '*', '*', "*" , 'Retry'),
('AAICheckVnfInMaintBB', '*', '*', '*', "*" , 'Abort'),
('AAISetVnfInMaintBB', '*', '*', '*', "*" , 'Abort'),
('SDNOVnfHealthCheckBB', '*', '*', '*', "*" , 'Abort'),
('AAIUnsetVnfInMaintBB', '*', '*', '*', "*" , 'Abort');