use catalogdb;

UPDATE building_block_detail SET RESOURCE_TYPE = "NETWORK_COLLECTION" WHERE BUILDING_BLOCK_NAME = "ActivateNetworkCollectionBB";
UPDATE building_block_detail SET RESOURCE_TYPE = "NETWORK_COLLECTION" WHERE BUILDING_BLOCK_NAME = "CreateNetworkCollectionBB";
UPDATE building_block_detail SET RESOURCE_TYPE = "NETWORK_COLLECTION" WHERE BUILDING_BLOCK_NAME = "DeleteNetworkCollectionBB";
UPDATE building_block_detail SET RESOURCE_TYPE = "NETWORK_COLLECTION" WHERE BUILDING_BLOCK_NAME = "DeactivateNetworkCollectionBB";
UPDATE building_block_detail SET TARGET_ACTION = "DEACTIVATE" WHERE BUILDING_BLOCK_NAME = "DeactivateNetworkCollectionBB";

INSERT into orchestration_status_state_transition_directive (RESOURCE_TYPE, ORCHESTRATION_STATUS, TARGET_ACTION, FLOW_DIRECTIVE) values
("NETWORK_COLLECTION", "PRECREATED", "CREATE", "CONTINUE"),
("NETWORK_COLLECTION", "ASSIGNED", "CREATE", "FAIL"),
("NETWORK_COLLECTION", "CREATED", "CREATE", "FAIL"),
("NETWORK_COLLECTION", "ACTIVE", "CREATE", "FAIL"),
("NETWORK_COLLECTION", "PENDING_CREATE", "CREATE", "FAIL"),
("NETWORK_COLLECTION", "PENDING_DELETE", "CREATE", "FAIL"),
("NETWORK_COLLECTION", "PENDING_ACTIVATION", "CREATE", "FAIL"),
("NETWORK_COLLECTION", "PENDING", "CREATE", "FAIL"),
("NETWORK_COLLECTION", "INVENTORIED", "CREATE", "SILENT_SUCCESS"),

("NETWORK_COLLECTION", "PRECREATED", "DELETE", "FAIL"),
("NETWORK_COLLECTION", "ASSIGNED", "DELETE", "FAIL"),
("NETWORK_COLLECTION", "CREATED", "DELETE", "FAIL"),
("NETWORK_COLLECTION", "ACTIVE", "DELETE", "CONTINUE"),
("NETWORK_COLLECTION", "PENDING_CREATE", "DELETE", "FAIL"),
("NETWORK_COLLECTION", "PENDING_DELETE", "DELETE", "FAIL"),
("NETWORK_COLLECTION", "PENDING_ACTIVATION", "DELETE", "FAIL"),
("NETWORK_COLLECTION", "PENDING", "DELETE", "FAIL"),
("NETWORK_COLLECTION", "INVENTORIED", "DELETE", "CONTINUE"),

("NETWORK_COLLECTION", "PRECREATED", "ACTIVE", "FAIL"),
("NETWORK_COLLECTION", "ASSIGNED", "ACTIVE", "FAIL"),
("NETWORK_COLLECTION", "CREATED", "ACTIVE", "FAIL"),
("NETWORK_COLLECTION", "ACTIVE", "ACTIVE", "SILENT_SUCCESS"),
("NETWORK_COLLECTION", "PENDING_CREATE", "ACTIVE", "FAIL"),
("NETWORK_COLLECTION", "PENDING_DELETE", "ACTIVE", "FAIL"),
("NETWORK_COLLECTION", "PENDING_ACTIVATION", "ACTIVE", "FAIL"),
("NETWORK_COLLECTION", "PENDING", "ACTIVE", "FAIL"),
("NETWORK_COLLECTION", "INVENTORIED", "ACTIVE", "CONTINUE");