use catalogdb;
 
CREATE TABLE if not exists `CONTROLLER_SELECTION_REFERENCE` (
  `VNF_TYPE` VARCHAR(50) NOT NULL,
  `CONTROLLER_NAME` VARCHAR(100) NOT NULL,
  `ACTION_CATEGORY` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`VNF_TYPE`, `CONTROLLER_NAME`, `ACTION_CATEGORY`)
  ) ENGINE = InnoDB DEFAULT CHARSET=latin1;