use catalogdb;

DROP TABLE vnf_vfmodule_cvnfc_configuration_customization;

CREATE TABLE IF NOT EXISTS vnf_vfmodule_cvnfc_configuration_customization (
  `ID` INT(11) NOT NULL AUTO_INCREMENT, 
  `MODEL_CUSTOMIZATION_UUID` VARCHAR(200) NOT NULL, 
  `MODEL_INSTANCE_NAME` VARCHAR(200) NOT NULL, 
  `CONFIGURATION_TYPE` VARCHAR(200) NULL, 
  `CONFIGURATION_ROLE` VARCHAR(200) NULL, 
  `CONFIGURATION_FUNCTION` VARCHAR(200) NULL, 
  `POLICY_NAME` VARCHAR(200) NULL, 
  `CREATION_TIMESTAMP` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `CONFIGURATION_MODEL_UUID` VARCHAR(200) NOT NULL,
  `VNF_RESOURCE_CUST_MODEL_CUSTOMIZATION_UUID` VARCHAR(200) DEFAULT NULL,
  `VF_MODULE_MODEL_CUSTOMIZATION_UUID` VARCHAR(200) DEFAULT NULL, 
  `CVNFC_CUSTOMIZATION_ID` INT(11) DEFAULT NULL,
  PRIMARY KEY (`ID`), 
  INDEX `fk_vnf_vfmodule_cvnfc_config_cust__configuration_idx` (`CONFIGURATION_MODEL_UUID` ASC), 
 
  CONSTRAINT `fk_vnf_vfmod_cvnfc_config_cust__configuration_resource` FOREIGN KEY (`CONFIGURATION_MODEL_UUID`) 
  REFERENCES `configuration` (`MODEL_UUID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB AUTO_INCREMENT = 20654 DEFAULT CHARACTER SET = LATIN1;