INSERT INTO orchestration_status_state_transition_directive(RESOURCE_TYPE, ORCHESTRATION_STATUS, TARGET_ACTION, FLOW_DIRECTIVE)
VALUES

('CONFIGURATION', 'ACTIVATED', 'UNASSIGN', 'FAIL'),
('CONFIGURATION', 'ACTIVATED', 'ASSIGN', 'SILENT_SUCCESS'),
('CONFIGURATION', 'ACTIVATED', 'ACTIVATE', 'SILENT_SUCCESS'),
('CONFIGURATION', 'ACTIVATED', 'DEACTIVATE', 'CONTINUE'),

('NETWORK', 'ACTIVATED', 'ASSIGN', 'SILENT_SUCCESS'),
('NETWORK', 'ACTIVATED', 'UNASSIGN', 'FAIL'),
('NETWORK', 'ACTIVATED', 'ACTIVATE', 'SILENT_SUCCESS'),
('NETWORK', 'ACTIVATED', 'DEACTIVATE', 'CONTINUE'),
('NETWORK', 'ACTIVATED', 'CREATE', 'SILENT_SUCCESS'),
('NETWORK', 'ACTIVATED', 'DELETE', 'FAIL'),
('NETWORK', 'ACTIVATED', 'UPDATE', 'CONTINUE'),
('NETWORK_COLLECTION', 'ACTIVATED', 'CREATE', 'FAIL'),
('NETWORK_COLLECTION', 'ACTIVATED', 'DELETE', 'CONTINUE'),
('NETWORK_COLLECTION', 'ACTIVATED', 'ACTIVATE', 'SILENT_SUCCESS'),

('NO_VALIDATE', 'ACTIVATED', 'CUSTOM', 'CONTINUE'),

('SERVICE', 'ACTIVATED', 'ASSIGN', 'SILENT_SUCCESS'),
('SERVICE', 'ACTIVATED', 'UNASSIGN', 'FAIL'),
('SERVICE', 'ACTIVATED', 'ACTIVATE', 'SILENT_SUCCESS'),
('SERVICE', 'ACTIVATED', 'DEACTIVATE', 'CONTINUE'),
('SERVICE', 'ACTIVATED', 'CHANGE_MODEL', 'CONTINUE'),

('VF_MODULE', 'ACTIVATED', 'ASSIGN', 'SILENT_SUCCESS'),
('VF_MODULE', 'ACTIVATED', 'UNASSIGN', 'FAIL'),
('VF_MODULE', 'ACTIVATED', 'ACTIVATE', 'SILENT_SUCCESS'),
('VF_MODULE', 'ACTIVATED', 'DEACTIVATE', 'CONTINUE'),
('VF_MODULE', 'ACTIVATED', 'CHANGE_MODEL', 'CONTINUE'),
('VF_MODULE', 'ACTIVATED', 'CREATE', 'SILENT_SUCCESS'),
('VF_MODULE', 'ACTIVATED', 'DELETE', 'FAIL'),

('VNF', 'ACTIVATED', 'ASSIGN', 'SILENT_SUCCESS'),
('VNF', 'ACTIVATED', 'UNASSIGN', 'FAIL'),
('VNF', 'ACTIVATED', 'ACTIVATE', 'SILENT_SUCCESS'),
('VNF', 'ACTIVATED', 'DEACTIVATE', 'CONTINUE'),
('VNF', 'ACTIVATED', 'CHANGE_MODEL', 'CONTINUE'),

('VOLUME_GROUP', 'ACTIVATED', 'ASSIGN', 'SILENT_SUCCESS'),
('VOLUME_GROUP', 'ACTIVATED', 'UNASSIGN', 'FAIL'),
('VOLUME_GROUP', 'ACTIVATED', 'ACTIVATE', 'SILENT_SUCCESS'),
('VOLUME_GROUP', 'ACTIVATED', 'DEACTIVATE', 'CONTINUE'),
('VOLUME_GROUP', 'ACTIVATED', 'CREATE', 'SILENT_SUCCESS'),
('VOLUME_GROUP', 'ACTIVATED', 'DELETE', 'FAIL');