/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 14 08:19:11 GMT 2016
 */

package org.openecomp.mso.db.catalog.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import java.sql.Timestamp;
import java.time.Instant;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.PrivateAccess;
import org.evosuite.runtime.System;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class VfModuleESTest extends VfModuleESTestscaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.setModelVersion("EzJ)~3C++");
      Integer integer0 = new Integer((-1));
      vfModule0.setVnfResourceId(integer0);
      vfModule0.getModelInvariantUuid();
      vfModule0.getModelInvariantUuid();
      VfModule vfModule1 = new VfModule();
      vfModule1.setDescription("");
      vfModule1.setIsBase((-1));
      Integer integer1 = new Integer((-289));
      vfModule1.setTemplateId(integer1);
      vfModule1.getTemplateId();
      vfModule1.setModelName("Yp{,,+-pFJp!Ym6r^");
      vfModule1.getDescription();
      vfModule0.setId((-1));
      vfModule0.setId((-4103));
      vfModule0.getId();
      vfModule1.getVnfResourceId();
      vfModule1.setTemplateId((Integer) null);
      Timestamp timestamp0 = new Timestamp((-3970L));
      vfModule0.setCreated(timestamp0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.isTheSameVersion("1&T-qG");
      Integer integer0 = new Integer((-385));
      Integer integer1 = Integer.valueOf((-385));
      Integer.toUnsignedString((-1));
      Integer.getInteger("", integer1);
      vfModule0.setVolTemplateId(integer0);
      vfModule0.setModelInvariantUuid("1&T-qG");
      vfModule0.toString();
      vfModule0.getIsBase();
      vfModule0.setModelVersion("VF=null,modelName=null,version=null,id=0,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=-385,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null");
      vfModule0.setType("wO");
      vfModule0.getType();
      vfModule0.isBase();
      vfModule0.getIsBase();
      vfModule0.setAsdcUuid("VF=");
      vfModule0.getModelVersion();
      vfModule0.setId(1);
      vfModule0.setModelName("VF=");
      vfModule0.getVolEnvironmentId();
      vfModule0.setVolTemplateId((Integer) null);
      vfModule0.setAsdcUuid("");
      vfModule0.setModelVersion("1&T-qG");
      vfModule0.isBase();
      vfModule0.getEnvironmentId();
      vfModule0.toString();
      vfModule0.getDescription();
      vfModule0.setType("");
      vfModule0.setVnfResourceId(integer1);
      System.setCurrentTimeMillis((-1L));
      vfModule0.getVnfResourceId();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      System.setCurrentTimeMillis(1L);
      VfModule vfModule0 = new VfModule();
      vfModule0.setModelInvariantUuid("57f9");
      vfModule0.setModelName("");
      vfModule0.getDescription();
      vfModule0.toString();
      vfModule0.setType("");
      vfModule0.getDescription();
      vfModule0.getCreated();
      vfModule0.setCreated((Timestamp) null);
      Integer integer0 = new Integer(2109);
      Integer integer1 = new Integer(1);
      Integer.getInteger("D}'htOb?", integer1);
      vfModule0.setVolEnvironmentId(integer0);
      vfModule0.getVnfResourceId();
      vfModule0.getModelName();
      System.setCurrentTimeMillis(0L);
      vfModule0.getModelName();
      vfModule0.getCreated();
      vfModule0.getModelName();
      vfModule0.getDescription();
      vfModule0.getDescription();
      vfModule0.getModelName();
      vfModule0.toString();
      vfModule0.getCreated();
      System.setCurrentTimeMillis(1L);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.setId(600);
      vfModule0.toString();
      Integer integer0 = new Integer((-1));
      Integer.divideUnsigned((-1), 1);
      Integer.min((-1), 1);
      Integer.max(2123, 600);
      Integer integer1 = new Integer(2123);
      vfModule0.setEnvironmentId(integer1);
      vfModule0.setEnvironmentId(integer0);
      vfModule0.isMoreRecentThan(",volEnvtId=");
      vfModule0.getId();
      Integer.compareUnsigned(467, (-1));
      vfModule0.setEnvironmentId(integer0);
      VfModule vfModule1 = new VfModule();
      vfModule1.isMoreRecentThan("VF=null,modelName=null,version=null,id=600,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=null,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null");
      vfModule1.toString();
      VfModule vfModule2 = new VfModule();
      vfModule0.getEnvironmentId();
      vfModule2.getDescription();
      vfModule2.setDescription((String) null);
      vfModule2.setModelVersion(", description=");
      vfModule2.toString();
      vfModule1.getModelInvariantUuid();
      vfModule1.toString();
      vfModule1.getEnvironmentId();
      vfModule0.setAsdcUuid("");
      vfModule0.setDescription((String) null);
      vfModule0.getIsBase();
      vfModule0.getAsdcUuid();
      vfModule0.getCreated();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.getDescription();
      Integer integer0 = new Integer(0);
      vfModule0.setVolTemplateId(integer0);
      vfModule0.setVersion((String) null);
      vfModule0.getDescription();
      vfModule0.setAsdcUuid((String) null);
      Integer integer1 = new Integer(0);
      Integer.getInteger((String) null);
      vfModule0.setVnfResourceId(integer1);
      vfModule0.setIsBase(1);
      vfModule0.getVolEnvironmentId();
      vfModule0.setId(0);
      vfModule0.getModelInvariantUuid();
      vfModule0.getEnvironmentId();
      vfModule0.getIsBase();
      vfModule0.setTemplateId(integer1);
      vfModule0.getCreated();
      vfModule0.getId();
      vfModule0.getCreated();
      vfModule0.getId();
      vfModule0.setModelInvariantUuid((String) null);
      vfModule0.getAsdcUuid();
      vfModule0.getVnfResourceId();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.getDescription();
      Integer integer0 = new Integer(0);
      Integer.divideUnsigned(1, 659);
      vfModule0.setVolTemplateId(integer0);
      vfModule0.setVersion((String) null);
      vfModule0.getDescription();
      vfModule0.setAsdcUuid((String) null);
      Integer integer1 = new Integer(0);
      Integer.getInteger((String) null);
      vfModule0.setVnfResourceId(integer1);
      vfModule0.setIsBase(1);
      vfModule0.getVolEnvironmentId();
      vfModule0.setId(0);
      vfModule0.getModelInvariantUuid();
      vfModule0.getEnvironmentId();
      vfModule0.getIsBase();
      vfModule0.setTemplateId(integer1);
      vfModule0.getCreated();
      vfModule0.getId();
      vfModule0.getCreated();
      vfModule0.getId();
      vfModule0.setModelInvariantUuid((String) null);
      vfModule0.getAsdcUuid();
      System.setCurrentTimeMillis((-1L));
      vfModule0.getTemplateId();
      vfModule0.getDescription();
      vfModule0.getAsdcUuid();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.getVolEnvironmentId();
      vfModule0.setEnvironmentId((Integer) null);
      assertNull(vfModule0.getModelVersion());
      
      Integer integer0 = new Integer(1);
      Integer.getInteger((String) null, (Integer) null);
      vfModule0.setEnvironmentId(integer0);
      vfModule0.setModelVersion((String) null);
      vfModule0.setId(171);
      vfModule0.toString();
      vfModule0.getEnvironmentId();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      Integer integer0 = Integer.valueOf((-2041));
      Integer.compareUnsigned((-2041), (-1));
      vfModule0.setTemplateId(integer0);
      vfModule0.setIsBase(3154);
      vfModule0.setModelInvariantUuid("");
      vfModule0.setDescription("nPVyq+_;@IZP:L");
      vfModule0.setId(883);
      vfModule0.toString();
      vfModule0.setIsBase((-2041));
      vfModule0.getTemplateId();
      vfModule0.getModelName();
      vfModule0.getVnfResourceId();
      vfModule0.toString();
      vfModule0.isBase();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.setIsBase(0);
      vfModule0.isMoreRecentThan(".");
      vfModule0.toString();
      vfModule0.setIsBase((-1465));
      vfModule0.setModelInvariantUuid("u5L");
      vfModule0.getIsBase();
      vfModule0.setId(0);
      vfModule0.getVolEnvironmentId();
      System.setCurrentTimeMillis((-1465));
      vfModule0.setModelVersion("VF=null,modelName=null,version=null,id=0,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=null,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null");
      vfModule0.setVersion("");
      vfModule0.toString();
      vfModule0.getAsdcUuid();
      vfModule0.getEnvironmentId();
      vfModule0.setVolEnvironmentId((Integer) null);
      vfModule0.getVnfResourceId();
      vfModule0.getDescription();
      vfModule0.getVolEnvironmentId();
      vfModule0.getCreated();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.isMoreRecentThan("zL");
      vfModule0.getType();
      vfModule0.setModelName((String) null);
      Integer integer0 = new Integer(0);
      Integer.getInteger("zL", (Integer) null);
      vfModule0.setType("");
      Integer.sum(34, 34);
      Integer.min(0, 2510);
      Integer.divideUnsigned(0, (-1));
      Integer.compare(0, 0);
      vfModule0.setVolEnvironmentId(integer0);
      vfModule0.setCreated((Timestamp) null);
      vfModule0.getCreated();
      vfModule0.getIsBase();
      vfModule0.setAsdcUuid("");
      vfModule0.setId(0);
      vfModule0.getModelVersion();
      vfModule0.setCreated((Timestamp) null);
      vfModule0.setModelVersion((String) null);
      vfModule0.getEnvironmentId();
      vfModule0.getVolEnvironmentId();
      vfModule0.getType();
      vfModule0.setAsdcUuid((String) null);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.setModelInvariantUuid("");
      vfModule0.setType(",modelName=");
      vfModule0.setModelVersion("");
      vfModule0.setModelName("+cQA/1wAo}o/T7,S");
      vfModule0.getVolTemplateId();
      vfModule0.getVolEnvironmentId();
      vfModule0.getVolTemplateId();
      vfModule0.getModelInvariantUuid();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      Integer integer0 = new Integer((-495));
      Integer.getInteger("M0@M@T", (-495));
      vfModule0.setVolEnvironmentId(integer0);
      vfModule0.setId(892);
      vfModule0.getTemplateId();
      vfModule0.toString();
      vfModule0.getVolEnvironmentId();
      vfModule0.setDescription("M0@M@T");
      vfModule0.getTemplateId();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      Integer integer0 = new Integer(2707);
      Integer integer1 = new Integer((-1));
      Integer.getInteger("", integer1);
      vfModule0.setVolEnvironmentId(integer0);
      vfModule0.getModelName();
      vfModule0.isMoreRecentThan("");
      vfModule0.getAsdcUuid();
      vfModule0.isMoreRecentThan((String) null);
      vfModule0.getVnfResourceId();
      vfModule0.toString();
      vfModule0.getCreated();
      vfModule0.getVolEnvironmentId();
      vfModule0.getModelName();
      vfModule0.getVnfResourceId();
      vfModule0.getVnfResourceId();
      vfModule0.getModelName();
      vfModule0.getAsdcUuid();
      vfModule0.getCreated();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.isMoreRecentThan((String) null);
      vfModule0.getCreated();
      vfModule0.setVolEnvironmentId((Integer) null);
      vfModule0.getVnfResourceId();
      Integer integer0 = new Integer(2983);
      vfModule0.isTheSameVersion((String) null);
      vfModule0.setDescription(")b,;fs\"&l\"#:Z");
      Integer.min(296, 0);
      vfModule0.setTemplateId(integer0);
      vfModule0.setType(")b,;fs\"&l\"#:Z");
      vfModule0.setModelInvariantUuid(")b,;fs\"&l\"#:Z");
      vfModule0.getId();
      vfModule0.setModelVersion("");
      vfModule0.getTemplateId();
      vfModule0.getModelVersion();
      vfModule0.setIsBase(2983);
      Integer integer1 = new Integer(0);
      try { 
        Integer.decode("X&-4c&g>;lQ`");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"X&-4c&g>;lQ`\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.toString();
      vfModule0.isMoreRecentThan("ql");
      vfModule0.toString();
      vfModule0.isMoreRecentThan("v;ese");
      vfModule0.getCreated();
      Integer integer0 = new Integer(0);
      Integer.getInteger("v;ese", 0);
      vfModule0.setVolTemplateId(integer0);
      vfModule0.isBase();
      vfModule0.getIsBase();
      vfModule0.setAsdcUuid("VF=null,modelName=null,version=null,id=0,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=null,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null");
      vfModule0.getId();
      vfModule0.getTemplateId();
      vfModule0.getVolTemplateId();
      vfModule0.getAsdcUuid();
      vfModule0.setId(0);
      Integer integer1 = new Integer(0);
      try { 
        Integer.parseUnsignedInt("ql", (-122));
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // radix -122 less than Character.MIN_RADIX
         //
         verifyException("java.lang.Integer", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      Integer integer0 = new Integer((-1847));
      vfModule0.setTemplateId(integer0);
      vfModule0.setVolTemplateId(integer0);
      vfModule0.getVolTemplateId();
      try { 
        Integer.decode("");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Zero length string
         //
         verifyException("java.lang.Integer", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      Integer integer0 = new Integer(1);
      vfModule0.setVolTemplateId(integer0);
      vfModule0.setType("");
      vfModule0.setDescription("");
      vfModule0.getVolTemplateId();
      vfModule0.getTemplateId();
      vfModule0.setModelInvariantUuid("");
      vfModule0.getType();
      vfModule0.setVersion("");
      vfModule0.getEnvironmentId();
      try { 
        Integer.decode("");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Zero length string
         //
         verifyException("java.lang.Integer", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      Integer integer0 = Integer.valueOf(797);
      vfModule0.setVnfResourceId(integer0);
      vfModule0.isMoreRecentThan("xApm&c~GA&l*X$");
      vfModule0.getVnfResourceId();
      vfModule0.getModelInvariantUuid();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.setModelVersion("");
      Integer integer0 = new Integer(1170);
      vfModule0.setVnfResourceId(integer0);
      vfModule0.getCreated();
      vfModule0.setVolTemplateId(integer0);
      vfModule0.setType("");
      vfModule0.setDescription("");
      vfModule0.getVnfResourceId();
      VfModule vfModule1 = new VfModule();
      vfModule1.setId((-1424));
      vfModule1.getVolTemplateId();
      vfModule1.getModelVersion();
      vfModule0.getId();
      vfModule0.setAsdcUuid("");
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      Integer integer0 = new Integer((-1483));
      Integer.toUnsignedString((-1742));
      Integer.toUnsignedString(0);
      Integer.getInteger("", (-1483));
      vfModule0.setModelVersion(".");
      Integer.divideUnsigned(0, 1371);
      vfModule0.setVolTemplateId(integer0);
      Integer.compare(1783, (-1404));
      vfModule0.setEnvironmentId(integer0);
      vfModule0.setVersion("");
      vfModule0.getModelVersion();
      vfModule0.getId();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.getId();
      vfModule0.setDescription("JZ)_Y_-H SVr5xC");
      Integer integer0 = new Integer(1266);
      Integer.remainderUnsigned(0, 1266);
      vfModule0.setEnvironmentId(integer0);
      vfModule0.getModelInvariantUuid();
      vfModule0.setDescription((String) null);
      vfModule0.getEnvironmentId();
      vfModule0.getModelName();
      vfModule0.getIsBase();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.setModelInvariantUuid(",version=");
      vfModule0.toString();
      vfModule0.toString();
      vfModule0.toString();
      vfModule0.isTheSameVersion("VF=null,modelName=null,version=null,id=0,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=null,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null");
      vfModule0.setId(1438);
      vfModule0.getVolTemplateId();
      Instant instant0 = MockInstant.ofEpochMilli(1438);
      Timestamp timestamp0 = Timestamp.from(instant0);
      timestamp0.clone();
      vfModule0.setCreated(timestamp0);
      vfModule0.setDescription(",version=");
      vfModule0.getTemplateId();
      vfModule0.getId();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.setModelVersion("EzJ)~3C++");
      Integer integer0 = new Integer((-1));
      vfModule0.setVnfResourceId(integer0);
      vfModule0.getModelInvariantUuid();
      vfModule0.getModelInvariantUuid();
      VfModule vfModule1 = new VfModule();
      vfModule1.setIsBase((-1));
      Integer integer1 = new Integer((-289));
      vfModule1.setTemplateId(integer1);
      vfModule1.getTemplateId();
      vfModule1.setModelName("Yp{,,+-pFJp!Ym6r^");
      vfModule1.getDescription();
      vfModule0.setId((-1));
      vfModule0.setId((-4103));
      vfModule0.getId();
      vfModule1.getVnfResourceId();
      vfModule1.setTemplateId((Integer) null);
      Timestamp timestamp0 = new Timestamp((-3970L));
      vfModule0.setCreated(timestamp0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.isTheSameVersion(", description=");
      vfModule0.setType("");
      Integer integer0 = new Integer(0);
      Integer.max(0, 0);
      Integer.min(0, 0);
      vfModule0.setEnvironmentId(integer0);
      vfModule0.setDescription("Kx6@ Rh^oX; 9s(c&>|");
      vfModule0.setId((-2750));
      vfModule0.setType((String) null);
      vfModule0.getDescription();
      vfModule0.setId(0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.setType("}f");
      vfModule0.setModelName("?2n6Dj");
      vfModule0.toString();
      vfModule0.getModelName();
      vfModule0.setAsdcUuid("?2n6Dj");
      vfModule0.getId();
      vfModule0.isTheSameVersion("");
      vfModule0.getAsdcUuid();
      vfModule0.getVolTemplateId();
      try { 
        Integer.parseUnsignedInt("6pu", 0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // radix 0 less than Character.MIN_RADIX
         //
         verifyException("java.lang.Integer", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      Timestamp timestamp0 = new Timestamp(0L);
      timestamp0.clone();
      timestamp0.setNanos(3848);
      vfModule0.setCreated(timestamp0);
      vfModule0.getVolTemplateId();
      Timestamp timestamp1 = vfModule0.getCreated();
      timestamp1.toInstant();
      Integer integer0 = new Integer(719);
      timestamp1.setNanos(3848);
      try { 
        Integer.parseUnsignedInt("1\t`FE9f:0z]~");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"1\t`FE9f:0z]~\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      Integer integer0 = new Integer(2069);
      Integer.compare(0, 0);
      Integer.min(2661, 2661);
      Integer.max(2069, 2069);
      vfModule0.setVnfResourceId(integer0);
      vfModule0.setDescription(",id=");
      vfModule0.isTheSameVersion(",id=");
      vfModule0.isMoreRecentThan(",id=");
      vfModule0.getEnvironmentId();
      vfModule0.setType("h4:pQoD8*M");
      vfModule0.getType();
      vfModule0.getType();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      Integer integer0 = new Integer(0);
      vfModule0.setEnvironmentId(integer0);
      vfModule0.setModelInvariantUuid("H'CQI+Q^^WoGt^Q2X]");
      vfModule0.toString();
      vfModule0.getModelInvariantUuid();
      Integer integer1 = vfModule0.getEnvironmentId();
      vfModule0.setVersion("");
      Integer.getInteger("", integer0);
      Integer.getInteger("", integer0);
      vfModule0.setVnfResourceId(integer1);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.toString();
      vfModule0.setModelVersion("VF=null,modelName=null,version=null,id=0,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=null,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null");
      vfModule0.setDescription("VF=null,modelName=null,version=null,id=0,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=null,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null");
      vfModule0.setId(0);
      vfModule0.getModelName();
      vfModule0.getAsdcUuid();
      Timestamp timestamp0 = new Timestamp((long) 0);
      timestamp0.toLocalDateTime();
      vfModule0.setCreated(timestamp0);
      vfModule0.getVolTemplateId();
      int int0 = vfModule0.getId();
      vfModule0.getTemplateId();
      vfModule0.setModelInvariantUuid((String) null);
      vfModule0.setType("VF=null,modelName=null,version=null,id=0,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=null,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null");
      Timestamp timestamp1 = vfModule0.getCreated();
      vfModule0.setDescription((String) null);
      vfModule0.setCreated(timestamp1);
      vfModule0.setVolTemplateId((Integer) null);
      vfModule0.getTemplateId();
      int int1 = vfModule0.getIsBase();
      assertTrue(int1 == int0);
      
      vfModule0.setModelVersion((String) null);
      boolean boolean0 = vfModule0.isBase();
      assertFalse(boolean0);
      
      vfModule0.setVolEnvironmentId((Integer) null);
      vfModule0.setModelInvariantUuid("VF=null,modelName=null,version=null,id=0,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=null,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null");
      vfModule0.getDescription();
      String string0 = vfModule0.toString();
      assertEquals("VF=VF=null,modelName=null,version=null,id=0,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=null,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null,modelName=null,version=null,id=0,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=null,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null,created=1/1/70 12:00 AM", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.setIsBase(1);
      vfModule0.getVnfResourceId();
      vfModule0.getEnvironmentId();
      vfModule0.toString();
      vfModule0.isBase();
      Integer integer0 = new Integer(0);
      vfModule0.getCreated();
      vfModule0.setAsdcUuid("VF=null,modelName=null,version=null,id=0,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=null,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null");
      vfModule0.getCreated();
      PrivateAccess.setVariable((Class<VfModule>) VfModule.class, vfModule0, "asdcUuid", (Object) "VF=null,modelName=null,version=null,id=0,vnfResourceId=null,templateId=null,envtId=null,volTemplateId=null,volEnvtId=null, description=null,asdcUuid=null,modelVersion=null");
      assertEquals(1, vfModule0.getIsBase());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      vfModule0.toString();
      vfModule0.getModelVersion();
      String string0 = vfModule0.getType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      VfModule vfModule0 = new VfModule();
      Integer integer0 = new Integer((-1));
      vfModule0.setVnfResourceId(integer0);
      vfModule0.getModelInvariantUuid();
      vfModule0.setTemplateId(integer0);
      vfModule0.setModelName((String) null);
      Timestamp timestamp0 = vfModule0.getCreated();
      assertNull(timestamp0);
  }
}
