/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 14 08:21:05 GMT 2016
 */

package org.openecomp.mso.db.catalog.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;

import java.sql.Timestamp;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class VnfResourceESTest extends VnfResourceESTestscaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.getAicVersionMax();
      Integer integer0 = new Integer(347);
      vnfResource0.setTemplateId(integer0);
      vnfResource0.toString();
      vnfResource0.setModelInvariantUuid(", vnfResourceId=");
      vnfResource0.getModelCustomizationName();
      vnfResource0.isTheSameVersion((String) null);
      vnfResource0.getId();
      Integer integer1 = new Integer(0);
      vnfResource0.setTemplateId(integer1);
      vnfResource0.setOrchestrationMode((String) null);
      vnfResource0.getModelName();
      vnfResource0.getId();
      vnfResource0.getEnvironmentId();
      vnfResource0.setModelName("");
      vnfResource0.getOrchestrationMode();
      vnfResource0.toString();
      vnfResource0.getModelName();
      vnfResource0.setModelCustomizationName(", vnfResourceId=");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setAicVersionMax("W8eoH");
      vnfResource0.setVnfType("");
      vnfResource0.setAicVersionMin("");
      vnfResource0.getServiceModelInvariantUUID();
      vnfResource0.setAsdcUuid("");
      VnfResource vnfResource1 = new VnfResource();
      vnfResource0.getTemplateId();
      vnfResource0.getVnfType();
      vnfResource0.setModelName("");
      vnfResource1.setModelCustomizationName((String) null);
      vnfResource0.getHeatFiles();
      vnfResource1.getModelName();
      vnfResource1.setDescription("");
      vnfResource1.setModelCustomizationName((String) null);
      vnfResource0.getEnvironmentId();
      vnfResource0.getAsdcUuid();
      vnfResource1.setVnfType("<[%6q]17$<ANY");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setAsdcUuid(",aicVersionMin=");
      vnfResource0.setOrchestrationMode(",aicVersionMin=");
      Integer integer0 = new Integer((-2387));
      vnfResource0.setEnvironmentId(integer0);
      vnfResource0.setModelCustomizationName("");
      vnfResource0.getHeatFiles();
      vnfResource0.setHeatFiles((Map<String, HeatFiles>) null);
      vnfResource0.setServiceModelInvariantUUID("");
      vnfResource0.getServiceModelInvariantUUID();
      vnfResource0.setDescription("");
      vnfResource0.getCreated();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setAicVersionMax("");
      vnfResource0.isTheSameVersion("ID=");
      vnfResource0.getModelCustomizationName();
      vnfResource0.getVnfType();
      vnfResource0.setModelInvariantUuid((String) null);
      vnfResource0.getHeatFiles();
      vnfResource0.setHeatFiles((Map<String, HeatFiles>) null);
      vnfResource0.toString();
      vnfResource0.setServiceModelInvariantUUID("");
      vnfResource0.setModelVersion("");
      vnfResource0.getCreated();
      vnfResource0.getCreated();
      vnfResource0.setVnfType("");
      Integer integer0 = new Integer(0);
      vnfResource0.setTemplateId(integer0);
      vnfResource0.getHeatFiles();
      vnfResource0.getAicVersionMax();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setServiceModelInvariantUUID("");
      vnfResource0.setId(1731);
      vnfResource0.setAsdcUuid((String) null);
      vnfResource0.setVersion((String) null);
      vnfResource0.setAsdcUuid((String) null);
      vnfResource0.getEnvironmentId();
      vnfResource0.setServiceModelInvariantUUID((String) null);
      vnfResource0.setId(1731);
      vnfResource0.getDescription();
      vnfResource0.setEnvironmentId((Integer) null);
      vnfResource0.getAicVersionMin();
      vnfResource0.getId();
      vnfResource0.setModelCustomizationName("`y0\"kaFz37W|^|'Y");
      vnfResource0.getId();
      vnfResource0.setVersion(",created=");
      vnfResource0.setModelInvariantUuid((String) null);
      vnfResource0.getCreated();
      vnfResource0.getAicVersionMax();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.isMoreRecentThan("2+Mv%?pGcj");
      vnfResource0.setAsdcUuid("2+Mv%?pGcj");
      vnfResource0.getModelInvariantUuid();
      vnfResource0.getModelVersion();
      vnfResource0.setVnfType("");
      vnfResource0.getVnfType();
      vnfResource0.setId(0);
      vnfResource0.getCreated();
      vnfResource0.getModelCustomizationName();
      vnfResource0.setDescription("");
      vnfResource0.getModelVersion();
      vnfResource0.getAicVersionMin();
      vnfResource0.getOrchestrationMode();
      vnfResource0.getDescription();
      vnfResource0.setAsdcUuid("");
      vnfResource0.setAicVersionMax(",template=");
      Integer integer0 = new Integer(4008);
      vnfResource0.setTemplateId(integer0);
      vnfResource0.setAicVersionMax(",aicVersionMax=");
      vnfResource0.setVnfType("");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.getHeatFiles();
      vnfResource0.setHeatFiles((Map<String, HeatFiles>) null);
      vnfResource0.isMoreRecentThan("");
      vnfResource0.toString();
      Integer integer0 = new Integer((-3414));
      vnfResource0.setEnvironmentId(integer0);
      vnfResource0.getEnvironmentId();
      vnfResource0.getCreated();
      vnfResource0.setModelInvariantUuid("");
      vnfResource0.setModelInvariantUuid("");
      vnfResource0.setAicVersionMin(",template=");
      vnfResource0.getEnvironmentId();
      vnfResource0.getServiceModelInvariantUUID();
      vnfResource0.getCreated();
      Integer integer1 = new Integer(898);
      vnfResource0.setTemplateId(integer1);
      vnfResource0.setModelVersion("VNF=null,version=null,mode=null,template=null,envtId=null,asdcUuid=null,aicVersionMin=null,aicVersionMax=null,modelInvariantUuid=null,modelVersion=null,modelCustomizationName=null,modelName=null,serviceModelInvariantUUID=null");
      vnfResource0.getHeatFiles();
      vnfResource0.getServiceModelInvariantUUID();
      vnfResource0.getId();
      VnfResource vnfResource1 = new VnfResource();
      vnfResource0.setId(0);
      vnfResource0.setId(1);
      vnfResource1.setServiceModelInvariantUUID(",template=");
      vnfResource1.setVnfType("");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.toString();
      Integer integer0 = new Integer(2830);
      vnfResource0.setEnvironmentId(integer0);
      vnfResource0.getAicVersionMin();
      vnfResource0.getModelCustomizationName();
      vnfResource0.getHeatFiles();
      vnfResource0.setHeatFiles((Map<String, HeatFiles>) null);
      vnfResource0.setId((-802));
      vnfResource0.getHeatFiles();
      vnfResource0.getAicVersionMin();
      vnfResource0.setOrchestrationMode((String) null);
      vnfResource0.setAicVersionMax((String) null);
      vnfResource0.setModelCustomizationName("mU");
      vnfResource0.getEnvironmentId();
      vnfResource0.setModelInvariantUuid((String) null);
      vnfResource0.getModelName();
      vnfResource0.getCreated();
      vnfResource0.getHeatFiles();
      vnfResource0.setModelCustomizationName(",template=");
      Integer integer1 = new Integer((-802));
      vnfResource0.setEnvironmentId(integer1);
      vnfResource0.getAicVersionMax();
      vnfResource0.setCreated((Timestamp) null);
      vnfResource0.getModelCustomizationName();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      Integer integer0 = new Integer((-850));
      vnfResource0.setTemplateId(integer0);
      vnfResource0.setAsdcUuid(",modelInvariantUuid=");
      vnfResource0.getAsdcUuid();
      vnfResource0.setVersion("M:u'/:}/c=[kT$1|~");
      vnfResource0.setVnfType("Sz!+cMn");
      vnfResource0.getTemplateId();
      vnfResource0.setId((-850));
      vnfResource0.getModelVersion();
      vnfResource0.setVersion("M:u'/:}/c=[kT$1|~");
      vnfResource0.setServiceModelInvariantUUID("M:u'/:}/c=[kT$1|~");
      vnfResource0.setVnfType((String) null);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      Integer integer0 = new Integer(0);
      vnfResource0.setTemplateId(integer0);
      vnfResource0.setModelVersion("");
      vnfResource0.getAsdcUuid();
      vnfResource0.setModelCustomizationName("e]B=gmKEhOL");
      vnfResource0.getModelVersion();
      vnfResource0.getHeatFiles();
      vnfResource0.setModelName("");
      vnfResource0.setDescription("v\u0000tj])h=a");
      vnfResource0.setAicVersionMax("v\u0000tj])h=a");
      vnfResource0.getAicVersionMin();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setModelInvariantUuid("");
      VnfResource vnfResource1 = new VnfResource();
      vnfResource1.getCreated();
      vnfResource0.setCreated((Timestamp) null);
      Integer integer0 = new Integer((-821));
      vnfResource0.setEnvironmentId(integer0);
      vnfResource0.setServiceModelInvariantUUID("");
      vnfResource0.setVnfType("[=");
      vnfResource0.getModelInvariantUuid();
      vnfResource0.getModelVersion();
      vnfResource0.setOrchestrationMode("");
      vnfResource1.setAicVersionMax("");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.getAicVersionMax();
      Integer integer0 = new Integer(0);
      vnfResource0.setTemplateId(integer0);
      vnfResource0.isMoreRecentThan((String) null);
      vnfResource0.setVnfType((String) null);
      vnfResource0.setServiceModelInvariantUUID(".");
      Integer integer1 = new Integer(1);
      vnfResource0.setTemplateId(integer1);
      vnfResource0.toString();
      vnfResource0.getModelCustomizationName();
      vnfResource0.setId(0);
      vnfResource0.setModelVersion(",modelVersion=");
      vnfResource0.getCreated();
      vnfResource0.setCreated((Timestamp) null);
      vnfResource0.getTemplateId();
      vnfResource0.getServiceModelInvariantUUID();
      vnfResource0.getModelInvariantUuid();
      vnfResource0.getEnvironmentId();
      vnfResource0.setAicVersionMax(",modelName=");
      Integer integer2 = new Integer((-777));
      vnfResource0.setTemplateId(integer2);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.getHeatFiles();
      vnfResource0.setHeatFiles((Map<String, HeatFiles>) null);
      vnfResource0.setModelName("Wwy:ofB");
      Integer integer0 = new Integer(0);
      vnfResource0.setTemplateId(integer0);
      Integer integer1 = new Integer(0);
      vnfResource0.setEnvironmentId(integer1);
      vnfResource0.setModelVersion("H[4j < uiNVQa.0w-P");
      vnfResource0.toString();
      vnfResource0.getModelInvariantUuid();
      vnfResource0.setVnfType("Wwy:ofB");
      vnfResource0.setAicVersionMin("]$0J9oRP[=9");
      vnfResource0.getModelName();
      vnfResource0.getVnfType();
      vnfResource0.getTemplateId();
      vnfResource0.getAicVersionMax();
      vnfResource0.setAsdcUuid("VNF=null,version=null,mode=null,template=0,envtId=0,asdcUuid=null,aicVersionMin=null,aicVersionMax=null,modelInvariantUuid=null,modelVersion=H[4j < uiNVQa.0w-P,modelCustomizationName=null,modelName=Wwy:ofB,serviceModelInvariantUUID=null");
      vnfResource0.getHeatFiles();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setModelCustomizationName("@%}qMRUUV?U7X~(re");
      vnfResource0.getEnvironmentId();
      vnfResource0.setOrchestrationMode("@%}qMRUUV?U7X~(re");
      vnfResource0.setEnvironmentId((Integer) null);
      vnfResource0.setModelName("@%}qMRUUV?U7X~(re");
      vnfResource0.getEnvironmentId();
      vnfResource0.toString();
      vnfResource0.setAsdcUuid("VNF=null,version=null,mode=@%}qMRUUV?U7X~(re,template=null,envtId=null,asdcUuid=null,aicVersionMin=null,aicVersionMax=null,modelInvariantUuid=null,modelVersion=null,modelCustomizationName=@%}qMRUUV?U7X~(re,modelName=@%}qMRUUV?U7X~(re,serviceModelInvariantUUID=null");
      vnfResource0.getAsdcUuid();
      vnfResource0.setAsdcUuid("l<;mp");
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.toString();
      vnfResource0.setModelName("KPE,e");
      vnfResource0.setAsdcUuid("KPE,e");
      vnfResource0.setAicVersionMax("KPE,e");
      vnfResource0.setAicVersionMin("");
      vnfResource0.setModelCustomizationName((String) null);
      vnfResource0.setDescription("UI!~W@$,");
      vnfResource0.setModelCustomizationName("UI!~W@$,");
      vnfResource0.setModelVersion(", description=null");
      Integer integer0 = new Integer((-1783));
      vnfResource0.setEnvironmentId(integer0);
      vnfResource0.getAicVersionMin();
      vnfResource0.getModelInvariantUuid();
      vnfResource0.setAsdcUuid("nsmO^IEr4");
      vnfResource0.getModelVersion();
      vnfResource0.setDescription("KPE,e");
      vnfResource0.setModelInvariantUuid((String) null);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.getAsdcUuid();
      vnfResource0.getHeatFiles();
      vnfResource0.setHeatFiles((Map<String, HeatFiles>) null);
      vnfResource0.setModelVersion("");
      Integer integer0 = new Integer(0);
      vnfResource0.setEnvironmentId(integer0);
      vnfResource0.setModelName("&");
      vnfResource0.getCreated();
      vnfResource0.getAsdcUuid();
      vnfResource0.setOrchestrationMode("");
      vnfResource0.setServiceModelInvariantUUID("");
      vnfResource0.setServiceModelInvariantUUID("&");
      vnfResource0.setModelInvariantUuid("");
      vnfResource0.setTemplateId(integer0);
      vnfResource0.getOrchestrationMode();
      vnfResource0.setOrchestrationMode((String) null);
      vnfResource0.getModelCustomizationName();
      VnfResource vnfResource1 = new VnfResource();
      vnfResource1.setAicVersionMax("");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setModelVersion("nT~K_A6F(}G");
      vnfResource0.getModelVersion();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      Integer integer0 = new Integer(4093);
      vnfResource0.setTemplateId(integer0);
      vnfResource0.setModelVersion("o)|85b9k");
      vnfResource0.isTheSameVersion("o)|85b9k");
      vnfResource0.getCreated();
      vnfResource0.setCreated((Timestamp) null);
      vnfResource0.getTemplateId();
      vnfResource0.toString();
      vnfResource0.getServiceModelInvariantUUID();
      vnfResource0.toString();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setAicVersionMax("e");
      vnfResource0.getAicVersionMax();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setAicVersionMax("s%I`;jJq\"jMHIJ");
      vnfResource0.getCreated();
      vnfResource0.setCreated((Timestamp) null);
      vnfResource0.setAicVersionMin("s%I`;jJq\"jMHIJ");
      vnfResource0.setVnfType("s%I`;jJq\"jMHIJ");
      vnfResource0.getVnfType();
      vnfResource0.setModelName("s%I`;jJq\"jMHIJ");
      vnfResource0.setModelVersion("s%I`;jJq\"jMHIJ");
      vnfResource0.getModelInvariantUuid();
      vnfResource0.setVnfType("s%I`;jJq\"jMHIJ");
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setModelName("hF&vbMtZNXOQ");
      vnfResource0.setDescription(",serviceModelInvariantUUID=");
      vnfResource0.setModelCustomizationName("?v>=ahb.RUT$");
      vnfResource0.getCreated();
      vnfResource0.setCreated((Timestamp) null);
      vnfResource0.setModelVersion("Vz:NMii");
      vnfResource0.setOrchestrationMode("Vz:NMii");
      vnfResource0.getEnvironmentId();
      VnfResource vnfResource1 = new VnfResource();
      vnfResource0.getModelName();
      vnfResource1.setId(0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setDescription((String) null);
      vnfResource0.setId((-1887));
      vnfResource0.getId();
      vnfResource0.toString();
      vnfResource0.toString();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setModelCustomizationName("lGX-!8UJxdrx]B'3");
      vnfResource0.setId(0);
      vnfResource0.setServiceModelInvariantUUID("");
      vnfResource0.setOrchestrationMode("lGX-!8UJxdrx]B'3");
      vnfResource0.setModelName("");
      vnfResource0.setServiceModelInvariantUUID("");
      vnfResource0.getModelCustomizationName();
      vnfResource0.setServiceModelInvariantUUID("");
      vnfResource0.setModelName("!{XY#&,~p1Ku");
      vnfResource0.getEnvironmentId();
      vnfResource0.getAicVersionMax();
      vnfResource0.getAicVersionMin();
      vnfResource0.setModelVersion(",fileName=");
      vnfResource0.toString();
      vnfResource0.toString();
      vnfResource0.setId(0);
      vnfResource0.getAsdcUuid();
      vnfResource0.getAsdcUuid();
      vnfResource0.setDescription("");
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      Integer integer0 = new Integer((-1033));
      vnfResource0.setTemplateId(integer0);
      vnfResource0.setAicVersionMin("?ph");
      vnfResource0.setVnfType("_LG54");
      vnfResource0.getAicVersionMin();
      vnfResource0.getEnvironmentId();
      vnfResource0.setDescription(",fileBody=");
      vnfResource0.toString();
      vnfResource0.getId();
      vnfResource0.setModelVersion(">dV");
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.getEnvironmentId();
      vnfResource0.setModelInvariantUuid((String) null);
      Integer integer0 = new Integer((-513));
      vnfResource0.setTemplateId(integer0);
      vnfResource0.setModelVersion("");
      Integer integer1 = new Integer(1650);
      vnfResource0.setTemplateId(integer1);
      vnfResource0.getHeatFiles();
      vnfResource0.getTemplateId();
      vnfResource0.getDescription();
      vnfResource0.getServiceModelInvariantUUID();
      Integer integer2 = new Integer(0);
      vnfResource0.setTemplateId(integer2);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setVnfType("");
      vnfResource0.setModelName("");
      vnfResource0.setDescription(",envtId=");
      vnfResource0.getDescription();
      vnfResource0.setVnfType(",envtId=");
      vnfResource0.setAicVersionMax("");
      vnfResource0.getOrchestrationMode();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setAicVersionMin("");
      vnfResource0.getModelInvariantUuid();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setVnfType("Va`9");
      vnfResource0.setModelVersion("gBfjaCmk_2B");
      vnfResource0.toString();
      vnfResource0.setVnfType("VNF=Va`9,version=null,mode=null,template=null,envtId=null,asdcUuid=null,aicVersionMin=null,aicVersionMax=null,modelInvariantUuid=null,modelVersion=gBfjaCmk_2B,modelCustomizationName=null,modelName=null,serviceModelInvariantUUID=null");
      vnfResource0.getModelCustomizationName();
      vnfResource0.setOrchestrationMode("Va`9");
      vnfResource0.getDescription();
      vnfResource0.getOrchestrationMode();
      vnfResource0.getServiceModelInvariantUUID();
      vnfResource0.getAsdcUuid();
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.getVnfType();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setVnfType("z?*}&4;|s");
      vnfResource0.setAicVersionMin("z?*}&4;|s");
      vnfResource0.toString();
      Map<String, HeatFiles> map0 = (Map<String, HeatFiles>) mock(Map.class, new ViolatedAssumptionAnswer());
      Timestamp timestamp0 = mock(Timestamp.class, new ViolatedAssumptionAnswer());
      doReturn(0L, 0L, 0L, 0L, 0L).when(timestamp0).getTime();
      doReturn((String) null, (String) null, (String) null, (String) null, (String) null).when(timestamp0).toString();
      vnfResource0.setCreated(timestamp0);
      vnfResource0.setHeatFiles(map0);
      vnfResource0.setServiceModelInvariantUUID("VNF=z?*}&4;|s,version=null,mode=null,template=null,envtId=null,asdcUuid=null,aicVersionMin=z?*}&4;|s,aicVersionMax=null,modelInvariantUuid=null,modelVersion=null,modelCustomizationName=null,modelName=null,serviceModelInvariantUUID=null");
      vnfResource0.toString();
      Timestamp timestamp1 = vnfResource0.getCreated();
      vnfResource0.toString();
      vnfResource0.toString();
      vnfResource0.toString();
      vnfResource0.setAicVersionMax("z?*}&4;|s");
      vnfResource0.setId(531);
      vnfResource0.getCreated();
      vnfResource0.toString();
      vnfResource0.getCreated();
      vnfResource0.getCreated();
      Timestamp timestamp2 = vnfResource0.getCreated();
      assertSame(timestamp2, timestamp1);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setVnfType("Va`9");
      vnfResource0.setModelVersion("gBfjaCmk_2B");
      vnfResource0.getModelCustomizationName();
      vnfResource0.getDescription();
      vnfResource0.getOrchestrationMode();
      vnfResource0.getServiceModelInvariantUUID();
      String string0 = vnfResource0.getAsdcUuid();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setOrchestrationMode("nT~K_A6F(}G");
      String string0 = vnfResource0.getModelVersion();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.setModelCustomizationName("");
      vnfResource0.toString();
      vnfResource0.setModelInvariantUuid("VNF=null,version=null,mode=null,template=null,envtId=null,asdcUuid=null,aicVersionMin=null,aicVersionMax=null,modelInvariantUuid=null,modelVersion=null,modelCustomizationName=,modelName=null,serviceModelInvariantUUID=null");
      Integer integer0 = new Integer(0);
      vnfResource0.setEnvironmentId(integer0);
      vnfResource0.getAicVersionMin();
      vnfResource0.getOrchestrationMode();
      vnfResource0.setModelName((String) null);
      vnfResource0.setVnfType("");
      vnfResource0.getHeatFiles();
      vnfResource0.setHeatFiles((Map<String, HeatFiles>) null);
      vnfResource0.getVnfType();
      vnfResource0.getEnvironmentId();
      vnfResource0.setVnfType("VNF=null,version=null,mode=null,template=null,envtId=null,asdcUuid=null,aicVersionMin=null,aicVersionMax=null,modelInvariantUuid=null,modelVersion=null,modelCustomizationName=,modelName=null,serviceModelInvariantUUID=null");
      vnfResource0.getModelCustomizationName();
      vnfResource0.getCreated();
      vnfResource0.getAicVersionMax();
      vnfResource0.getModelInvariantUuid();
      vnfResource0.setTemplateId(integer0);
      vnfResource0.setAsdcUuid("");
      assertNull(vnfResource0.getServiceModelInvariantUUID());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      VnfResource vnfResource0 = new VnfResource();
      vnfResource0.getDescription();
      vnfResource0.setVnfType("8@%dK*Sm}Sc[/\"*^vL");
      vnfResource0.setAicVersionMax("8@%dK*Sm}Sc[/\"*^vL");
      vnfResource0.setModelCustomizationName((String) null);
      vnfResource0.setDescription(";bAY~(4TDJ[r4<!nHi");
      int int0 = vnfResource0.getId();
      assertEquals(0, int0);
      
      vnfResource0.getTemplateId();
      Integer integer0 = new Integer((-886));
      vnfResource0.setTemplateId(integer0);
      vnfResource0.getAicVersionMin();
      vnfResource0.setAicVersionMax(",aicVers?onMhx=");
      Integer integer1 = new Integer(0);
      vnfResource0.getModelName();
      assertEquals(0, vnfResource0.getId());
  }
}
