/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 14 09:21:05 GMT 2016
 */

package org.openecomp.mso.adapters.nwrest;

import org.junit.Test;
import static org.junit.Assert.*;

import org.openecomp.mso.openstack.exceptions.MsoExceptionCategory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class CreateNetworkErrorESTest extends CreateNetworkErrorESTestscaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CreateNetworkError createNetworkError0 = new CreateNetworkError();
      assertNull(createNetworkError0.getMessageId());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MsoExceptionCategory msoExceptionCategory0 = MsoExceptionCategory.INTERNAL;
      CreateNetworkError createNetworkError0 = new CreateNetworkError(".iOuG[TmaW", msoExceptionCategory0, false, "&j1e*8kgmi]:2n?(");
      assertEquals("&j1e*8kgmi]:2n?(", createNetworkError0.getMessageId());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CreateNetworkError createNetworkError0 = new CreateNetworkError("");
      assertNull(createNetworkError0.getCategory());
  }
}
