/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 14 09:20:47 GMT 2016
 */

package org.openecomp.mso.adapters.nwrest;

import org.junit.Test;
import static org.junit.Assert.*;

import org.openecomp.mso.openstack.exceptions.MsoExceptionCategory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class DeleteNetworkErrorESTest extends DeleteNetworkErrorESTestscaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MsoExceptionCategory msoExceptionCategory0 = MsoExceptionCategory.IO;
      DeleteNetworkError deleteNetworkError0 = new DeleteNetworkError("9X", msoExceptionCategory0, false, "ew9AjW>{Sk.");
      assertEquals("9X", deleteNetworkError0.getMessage());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DeleteNetworkError deleteNetworkError0 = new DeleteNetworkError();
      assertNull(deleteNetworkError0.getCategory());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DeleteNetworkError deleteNetworkError0 = new DeleteNetworkError("9X");
      assertNull(deleteNetworkError0.getCategory());
  }
}
