/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 14 09:17:33 GMT 2016
 */

package org.openecomp.mso.adapters.nwrest;

import org.junit.Test;
import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class QueryNetworkErrorESTest extends QueryNetworkErrorESTestscaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QueryNetworkError queryNetworkError0 = new QueryNetworkError();
      assertNull(queryNetworkError0.getMessage());
  }
}
