server:
  port: 8087
 
spring:
  security:
    usercredentials:
    -  
      username: sdnc
      password: '$2b$10$byoF5q.VngZd8nj63q2Rm.bbAGUQrNG3DliPtc5l9nJIbXpXyCfrG'
      role: SDNC-Client
    -  
      username: sitecontrol
      password: '$2b$10$byoF5q.VngZd8nj63q2Rm.bbAGUQrNG3DliPtc5l9nJIbXpXyCfrG'
      role: SiteControl-Client 
    -  
      username: bpel
      password: '$2b$10$byoF5q.VngZd8nj63q2Rm.bbAGUQrNG3DliPtc5l9nJIbXpXyCfrG'
      role: BPEL-Client        
    -  
      username: sniro
      password: '$2b$10$byoF5q.VngZd8nj63q2Rm.bbAGUQrNG3DliPtc5l9nJIbXpXyCfrG'
      role: SNIRO-Client  
    -  
      username: apih
      password: '$2b$10$byoF5q.VngZd8nj63q2Rm.bbAGUQrNG3DliPtc5l9nJIbXpXyCfrG'
      role: MSO-Client
    -  
      username: mso_admin
      password: '$2b$10$byoF5q.VngZd8nj63q2Rm.bbAGUQrNG3DliPtc5l9nJIbXpXyCfrG'
      role: ACTUATOR


org:
  onap:
    so:
      adapters:
        default_keystone_url_version: /v2.0
        default_keystone_reg_ex: "/[vV][0-9]"
        vnf:
          bpelauth: 5119D1AF37F671FC01FFAD2151D93EFB2BBB503E879FD07104D024EDDF118FD1
          checkRequiredParameters: true
          addGetFilesOnVolumeReq: false
          sockettimeout: 30
          connecttimeout: 30
          retrycount: 5
          retryinterval: -15
          retrylist: 408,429,500,502,503,504,900
          valet_enabled: false
          fail_requests_on_valet_failure: false
        network:
          bpelauth: 5119D1AF37F671FC01FFAD2151D93EFB2BBB503E879FD07104D024EDDF118FD1
          sockettimeout: 5
          connecttimeout: 5
          retrycount: 5
          retryinterval: -15
          retrylist: 408,429,500,502,503,504,900
        tenant: 
          default_keystone_url_version: /v2.0
          default_keystone_reg_ex: "/[vV][0-9]"
          default_tenant_description: Tenant
          default_region_type: single
          default_user_role: admin
          default_success_status_string: Success
          default_no_regions_status_string: no regions
          default_quota_value: 10
          set_default_quota: false
 
ecomp:
  mso:
    adapters:
      po:
        retryCodes: 504
        retryDelay: 5
        retryCount: 3
        pollTimeout: 7500
        pollInterval: 15
      
mso:
  logPath: ./logs/openstack
  catalog:
    db:
      spring:
        endpoint: http://c1.vm1.mso.simpledemo.openecomp.org:8082
  db:
    auth: Basic YnBlbDptc28tZGItMTUwNyE=
  site-name: localDevEnv
  async:
    core-pool-size: 50
    max-pool-size: 50
    queue-capacity: 500

cloud_config:
  identity_services:
    RAX_KEYSTONE:
      identity_url: "https://identity.api.rackspacecloud.com/v2.0"
      mso_id: "RACKSPACE_ACCOUNT_ID"
      mso_pass: "RACKSPACE_ACCOUNT_APIKEY"
      admin_tenant: "service"
      member_role: "admin"
      tenant_metadata: true
      identity_server_type: "KEYSTONE"
      identity_authentication_type: "RACKSPACE_APIKEY"   
  cloud_sites:
    Dallas:
      region_id: "DFW"
      clli: "DFW"
      aic_version: "2.5"
      identity_service_id: "RAX_KEYSTONE"
    Northern Virginia:
      region_id: "IAD"
      clli: "IAD"
      aic_version: "2.5"
      identity_service_id: "RAX_KEYSTONE"
    Chicago:
      region_id: "ORD"
      clli: "ORD"
      aic_version: "2.5"
      identity_service_id: "RAX_KEYSTONE" 
    DEFAULT:
      region_id: "DFW"
      clli: "DFW"
      aic_version: "2.5"
      identity_service_id: "RAX_KEYSTONE"