apiVersion: v1
kind: Service
metadata: 
  labels:
    app: asdc-controller 
  name: asdc-controller
  namespace: com-att-mso-dev
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: asdc-controller 
  type: NodePort
