apiVersion: v1
kind: Service
metadata:
  name: mchanmsosvc
  labels:
    app: mchanmsopod
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: mchanmsopod