server:
    port: 8091
    tomcat:
        max-threads: 50
ssl-enable: false
mso:
  logPath: logs
  site-name: localSite
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/requestdb
    username: mso
    password: mso123
    driver-class-name: org.mariadb.jdbc.Driver
    initialize: true
    initialization-mode: never
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      enable-lazy-load-no-trans: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    usercredentials:
    -
      username: bpel
      password: '$2a$12$1xyutEZNfjGewIZRfKaE8eZE99f5sYFUmmM80BobI65KNjmcK0JuO'
      role: BPEL-Client
    -
      username: mso_admin
      password: '$2a$12$tidKuu.h88E2nuL95pTVY.ZOYMN/1dp29A9b1o.0GFDsVVSYlMkHa'
      role: ACTUATOR
