server:
  port: 8080

spring:
  security:
    usercredentials:
    -  
      username: asdc
      password: '$2b$10$byoF5q.VngZd8nj63q2Rm.bbAGUQrNG3DliPtc5l9nJIbXpXyCfrG'
      role: Asdc-Client
    -  
      username: mso_admin
      password: '$2b$10$byoF5q.VngZd8nj63q2Rm.bbAGUQrNG3DliPtc5l9nJIbXpXyCfrG'
      role: ACTUATOR

mso:
  logPath: ./logs/asdc
  catalog:
    db:
      spring:
        endpoint: http://c1.vm1.mso.simpledemo.openecomp.org:8082
  db:
    auth: Basic YnBlbDpwYXNzd29yZDEk
  site-name: onapheat
  aai:  
    endpoint: https://aai.api.simpledemo.onap.org:8443
  asdc-connections:
    asdc-controller1:
      user: mso
      consumerGroup: sdc-OpenSource-Env1
      consumerId: sdc-COpenSource-Env11
      environmentName: SDC-OpenSource-Env1
      asdcAddress: c2.vm1.sdc.simpledemo.openecomp.org:8443
      password: 613AF3483E695524F9857643B697FA51C7A9A0951094F53791485BF3458F9EADA37DBACCCEBD0CB242B85B4062745247
      pollingInterval: 60
      pollingTimeout: 60
      relevantArtifactTypes: HEAT,HEAT_ENV,HEAT_VOL
      activateServerTLSAuth: false
      keyStorePassword:  
      keyStorePath:
      watchDogTimeout: 60
      isFitlerInEmptyResources: true
      messageBusAddress: c2.vm1.sdc.simpledemo.openecomp.org
  asdc:
    config:
      key: 566B754875657232314F5548556D3665
      components:
        count: 3,
        componentNames: SO,AAI,SDNC
  scheduling:
    enabled: false