<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:sdncadaptersc="http://org.onap/workflow/sdnc/adapter/schema/v1"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://org.onap/workflow/sdnc/adapter/callback/wsdl/v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://org.onap/workflow/sdnc/adapter/callback/wsdl/v1">
	<types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema"
			elementFormDefault="qualified"
			targetNamespace="http://org.onap/workflow/sdnc/adapter/wsdl/v1">
			<import namespace="http://org.onap/workflow/sdnc/adapter/schema/v1"
				schemaLocation="SDNCAdapterSchema.xsd" />
		</schema>
	</types>

	<message name="SDNCAdapterCallbackRequest">
		<part element="sdncadaptersc:SDNCAdapterCallbackRequest" name="SDNCAdapterCallbackRequest">
		</part>
	</message>

	<message name="SDNCAdapterCallbackResponse">
		<part element="sdncadaptersc:SDNCAdapterResponse" name="SDNCAdapterCallbackResponse">
		</part>
	</message>

	<portType name="SDNCCallbackAdapterPortType">
		<operation name="SDNCAdapterCallback">
			<input message="tns:SDNCAdapterCallbackRequest" name="SDNCAdapterCallbackRequest">
			</input>
			<output message="tns:SDNCAdapterCallbackResponse" name="SDNCAdapterCallbackResponse">
			</output>
		</operation>
	</portType>
	
	<binding name="SDNCCallbackAdapterSoapHttpBinding" type="tns:SDNCCallbackAdapterPortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="SDNCAdapterCallback">
			<soap:operation soapAction="" style="document" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<service name="SDNCCallbackAdapterService">
		<port binding="tns:SDNCCallbackAdapterSoapHttpBinding" name="SDNCCallbackAdapterSoapHttpPort">
			<soap:address location="SDNCCallbackAdapterService" />
		</port>
	</service>
</definitions>
