/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 14 11:35:52 GMT 2016
 */

package org.openecomp.mso.bpmn.core;

import org.junit.Test;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class MissingInjectedFieldExceptionESTest extends MissingInjectedFieldExceptionESTestscaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MissingInjectedFieldException missingInjectedFieldException0 = new MissingInjectedFieldException("", "");
  }
}
