use requestdb;

ALTER TABLE active_requests
ADD VPN_ID varchar(200),
ADD PROGRESS BIGINT(20),
ADD STATUS_MESSAGE LONGTEXT,
ADD REQUESTED_SERVICE_NAME varchar(200),
ADD PRODUCT_FLAVOR varchar(200),
ADD SERVICE_INSTANCE_NAME varchar(80);
