use requestdb;

CREATE TABLE IF NOT EXISTS request_processing_data (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `SO_REQUEST_ID` VARCHAR(50) NOT NULL,
  `GROUPING_ID` VARCHAR(100) NULL,
  `NAME` VARCHAR(200) NOT NULL,
  `VALUE` LONGTEXT,
  `TAG` VARCHAR(200) NOT NULL,
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `UK_request_processing_data` (
    `SO_REQUEST_ID` ASC,
    `GROUPING_ID` ASC,
    `TAG` ASC,
    `NAME` ASC
  )
) ENGINE = InnoDB DEFAULT CHARSET = latin1;
