use requestdb;

CREATE TABLE IF NOT EXISTS cloud_api_requests(
`ID` INT(13) NOT NULL AUTO_INCREMENT,
`REQUEST_BODY` LONGTEXT NOT NULL,
`CLOUD_IDENTIFIER` VARCHAR(200) NULL,
`SO_REQUEST_ID` VARCHAR(45) NOT NULL,
`CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`ID`),
CONSTRAINT fk_cloud_api_req_infra_requests
    FOREIGN KEY (SO_REQUEST_ID)
    REFERENCES infra_active_requests (REQUEST_ID))
ENGINE = InnoDB DEFAULT CHARSET=latin1;