/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 14 09:04:06 GMT 2016
 */

package org.openecomp.mso.logger;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;

@EvoSuiteClassExclude
public class MsoLoggingServletESTestscaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.openecomp.mso.logger.MsoLoggingServlet"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init(); 
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
     
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MsoLoggingServletESTestscaffolding.class.getClassLoader() ,
      "org.jboss.resteasy.spi.StringConverter",
      "org.apache.xerces.impl.XMLEntityManager$CharacterBufferPool",
      "org.apache.xerces.xni.XMLResourceIdentifier",
      "org.apache.xerces.impl.XMLEntityManager",
      "org.apache.xerces.impl.dtd.XMLDTDDescription",
      "com.att.eelf.i18n.EELFMsgs",
      "org.jboss.resteasy.util.ThreadLocalStack",
      "org.apache.xerces.impl.dv.InvalidDatatypeValueException",
      "org.apache.xerces.jaxp.UnparsedEntityHandler",
      "org.apache.xerces.parsers.AbstractXMLDocumentParser",
      "org.apache.xerces.impl.XMLScanner",
      "org.apache.xerces.impl.dv.dtd.NOTATIONDatatypeValidator",
      "org.apache.xerces.xni.parser.XMLParseException",
      "org.apache.xerces.impl.XMLEntityScanner",
      "org.apache.xerces.util.URI$MalformedURIException",
      "org.apache.xerces.impl.XMLNSDocumentScannerImpl",
      "org.jboss.resteasy.core.interception.JaxrsInterceptorRegistry",
      "org.apache.xerces.impl.dtd.models.CMAny",
      "org.apache.xerces.util.URI",
      "org.apache.xerces.xni.parser.XMLDocumentFilter",
      "org.apache.xerces.xni.parser.XMLDTDSource",
      "org.apache.xerces.impl.dtd.XMLAttributeDecl",
      "org.apache.xerces.parsers.XMLParser",
      "org.jboss.resteasy.spi.ResteasyProviderFactory",
      "org.apache.xerces.util.SymbolTable",
      "org.apache.xerces.impl.io.Latin1Reader",
      "org.apache.xerces.impl.dv.ValidationContext",
      "org.jboss.resteasy.spi.BadRequestException",
      "org.apache.xerces.impl.dtd.XMLDTDValidator",
      "org.apache.xerces.impl.dtd.XML11NSDTDValidator",
      "org.openecomp.mso.logger.MsoLoggingServlet",
      "org.apache.xerces.util.AugmentationsImpl",
      "org.jboss.resteasy.core.interception.ReaderInterceptorRegistry",
      "org.apache.xerces.impl.dv.ObjectFactory",
      "org.jboss.resteasy.client.exception.mapper.ClientExceptionMapper",
      "org.apache.xerces.impl.dv.DatatypeValidator",
      "org.jboss.resteasy.spi.InjectorFactory",
      "org.jboss.resteasy.core.interception.LegacyPrecedence",
      "org.apache.xerces.jaxp.SAXParserImpl",
      "org.apache.xerces.xni.grammars.XMLGrammarDescription",
      "org.jboss.resteasy.plugins.delegates.NewCookieHeaderDelegate",
      "org.apache.xerces.xni.parser.XMLErrorHandler",
      "org.apache.xerces.util.MessageFormatter",
      "org.apache.xerces.impl.XMLEntityManager$1",
      "org.apache.xerces.xni.parser.XMLDTDScanner",
      "org.openecomp.mso.logger.MsoLogger$ErrorCode",
      "org.apache.xerces.xni.XMLAttributes",
      "org.apache.xerces.impl.dv.dtd.StringDatatypeValidator",
      "org.apache.xerces.impl.io.MalformedByteSequenceException",
      "org.apache.xerces.impl.Constants$ArrayEnumeration",
      "org.jboss.resteasy.core.interception.WriterInterceptorRegistry",
      "org.apache.xerces.impl.dv.DTDDVFactory",
      "org.apache.xerces.impl.dv.dtd.IDDatatypeValidator",
      "org.apache.xerces.impl.validation.ValidationManager",
      "org.apache.xerces.xni.XNIException",
      "org.apache.xerces.impl.dtd.models.CMNode",
      "org.apache.xerces.xni.parser.XMLDocumentSource",
      "org.apache.xerces.xni.XMLDTDContentModelHandler",
      "org.jboss.resteasy.spi.StringParameterUnmarshaller",
      "org.jboss.resteasy.core.MediaTypeMap",
      "org.openecomp.mso.logger.MsoLogger$Catalog",
      "org.apache.xerces.util.AugmentationsImpl$SmallContainer",
      "org.apache.xerces.impl.XMLErrorReporter",
      "org.jboss.resteasy.specimpl.ResteasyUriBuilder",
      "org.apache.xerces.impl.Constants",
      "org.apache.xerces.util.XMLStringBuffer",
      "org.apache.xerces.jaxp.JAXPConstants",
      "org.apache.xerces.xni.parser.XMLParserConfiguration",
      "org.apache.xerces.xni.XMLString",
      "org.apache.xerces.impl.dv.DVFactoryException",
      "org.apache.xerces.impl.dv.DatatypeException",
      "org.apache.xerces.parsers.XML11Configurable",
      "org.apache.xerces.parsers.XIncludeAwareParserConfiguration",
      "org.jboss.resteasy.logging.Logger$LoggerType",
      "org.apache.xerces.impl.xs.identity.FieldActivator",
      "org.apache.xerces.impl.XMLEntityScanner$1",
      "org.apache.xerces.jaxp.SAXParserFactoryImpl",
      "org.jboss.resteasy.util.CaseInsensitiveMap$CaseInsensitiveComparator",
      "org.apache.xerces.xs.ElementPSVI",
      "org.apache.xerces.parsers.AbstractSAXParser",
      "org.jboss.resteasy.spi.LoggableFailure",
      "org.apache.xerces.xni.parser.XMLDTDFilter",
      "org.apache.xerces.xni.parser.XMLDTDContentModelSource",
      "org.openecomp.mso.entity.MsoRequest",
      "org.apache.xerces.xni.XMLLocator",
      "org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser",
      "org.apache.xerces.xni.Augmentations",
      "org.apache.xerces.impl.XMLEntityHandler",
      "org.jboss.resteasy.util.CaseInsensitiveMap$1",
      "org.jboss.resteasy.specimpl.BuiltResponse",
      "org.jboss.resteasy.core.Headers",
      "org.apache.xerces.xni.parser.XMLComponent",
      "org.apache.xerces.impl.dv.dtd.ListDatatypeValidator",
      "org.jboss.resteasy.spi.Failure",
      "org.apache.xerces.impl.XMLEntityManager$ScannedEntity",
      "org.apache.xerces.jaxp.JAXPValidatorComponent",
      "org.apache.xerces.xni.parser.XMLDTDContentModelFilter",
      "org.apache.xerces.xs.PSVIProvider",
      "org.apache.xerces.impl.XMLEntityManager$ByteBufferPool",
      "org.jboss.resteasy.specimpl.ResponseBuilderImpl",
      "org.jboss.resteasy.core.interception.ClientResponseFilterRegistry",
      "org.apache.xerces.impl.dtd.XMLEntityDecl",
      "org.apache.xerces.xs.ItemPSVI",
      "org.jboss.resteasy.specimpl.MultivaluedTreeMap",
      "org.apache.xerces.impl.dv.dtd.ENTITYDatatypeValidator",
      "org.apache.xerces.xni.parser.XMLEntityResolver",
      "org.jboss.resteasy.client.core.ClientErrorInterceptor",
      "org.apache.xerces.impl.dtd.XMLNSDTDValidator",
      "org.apache.xerces.impl.XMLDTDScannerImpl",
      "org.apache.xerces.impl.dv.dtd.NMTOKENDatatypeValidator",
      "org.apache.xerces.parsers.ObjectFactory",
      "org.jboss.resteasy.spi.ResteasyProviderFactory$SortedKey",
      "org.apache.xerces.xni.parser.XMLConfigurationException",
      "org.apache.xerces.impl.XML11NSDocumentScannerImpl",
      "org.apache.xerces.parsers.SAXParser",
      "com.att.eelf.i18n.EELFResolvableErrorEnum",
      "org.apache.xerces.impl.XMLEntityManager$RewindableInputStream",
      "org.jboss.resteasy.core.interception.ContainerRequestFilterRegistry",
      "org.jboss.resteasy.specimpl.VariantListBuilderImpl",
      "org.apache.xerces.xni.parser.XMLInputSource",
      "org.apache.xerces.xni.parser.XMLComponentManager",
      "com.att.eelf.configuration.EELFLogger$Level",
      "org.jboss.resteasy.core.interception.JaxrsInterceptorRegistry$InterceptorFactory",
      "org.apache.xerces.impl.io.UTF8Reader",
      "org.apache.xerces.impl.dtd.XMLSimpleType",
      "org.apache.xerces.impl.XML11DocumentScannerImpl",
      "org.apache.xerces.util.AugmentationsImpl$AugmentationsItemsContainer",
      "org.apache.xerces.util.XMLChar",
      "org.apache.xerces.impl.XML11DTDScannerImpl",
      "org.apache.xerces.impl.dtd.XMLElementDecl",
      "com.att.eelf.i18n.EELFResourceManager$RESOURCE_TYPES",
      "org.apache.xerces.xni.grammars.Grammar",
      "org.apache.xerces.impl.dtd.models.ContentModelValidator",
      "com.att.eelf.configuration.EELFLogger",
      "org.apache.xerces.xni.grammars.XMLGrammarLoader",
      "org.apache.xerces.xni.XMLDocumentHandler",
      "org.apache.xerces.impl.io.UCSReader",
      "org.apache.xerces.impl.XMLEntityManager$CharacterBuffer",
      "org.apache.xerces.impl.validation.ValidationState",
      "org.apache.xerces.impl.XMLEntityManager$Entity",
      "org.jboss.resteasy.spi.HttpRequest",
      "org.apache.xerces.util.XMLResourceIdentifierImpl",
      "org.jboss.resteasy.logging.Logger",
      "org.jboss.resteasy.spi.ConstructorInjector",
      "org.apache.xerces.xni.NamespaceContext",
      "org.apache.xerces.impl.dtd.XMLDTDLoader",
      "org.jboss.resteasy.util.CaseInsensitiveMap",
      "org.apache.xerces.util.XMLSymbols",
      "org.apache.xerces.parsers.ObjectFactory$ConfigurationError",
      "org.jboss.resteasy.core.interception.ContainerResponseFilterRegistry",
      "org.apache.xerces.impl.io.ASCIIReader",
      "org.jboss.resteasy.core.interception.InterceptorRegistry",
      "org.apache.xerces.impl.dtd.XMLDTDProcessor",
      "org.apache.xerces.impl.XMLDocumentFragmentScannerImpl",
      "org.apache.xerces.impl.XML11EntityScanner",
      "org.apache.xerces.impl.dtd.DTDGrammar",
      "org.apache.xerces.impl.dv.dtd.IDREFDatatypeValidator",
      "com.att.eelf.configuration.SLF4jWrapper",
      "org.apache.xerces.impl.dv.dtd.DTDDVFactoryImpl",
      "org.apache.xerces.impl.dtd.XMLContentSpec",
      "org.openecomp.mso.logger.MsoLogger",
      "org.apache.xerces.xs.AttributePSVI",
      "org.apache.xerces.impl.dtd.DTDGrammarBucket",
      "org.apache.xerces.impl.msg.XMLMessageFormatter",
      "org.apache.xerces.xni.parser.XMLDocumentScanner",
      "org.apache.xerces.impl.XMLVersionDetector",
      "org.apache.xerces.impl.XMLDocumentScannerImpl",
      "org.apache.xerces.xni.parser.XMLPullParserConfiguration",
      "org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$Dispatcher",
      "org.apache.xerces.impl.xs.XMLSchemaValidator",
      "org.apache.xerces.xni.grammars.XMLDTDDescription",
      "org.jboss.resteasy.logging.impl.Slf4jLogger",
      "org.apache.xerces.xni.QName",
      "org.apache.xerces.jaxp.TeeXMLDocumentFilterImpl",
      "org.apache.xerces.util.XMLAttributesImpl",
      "org.apache.xerces.impl.XMLEntityManager$InternalEntity",
      "org.apache.xerces.impl.RevalidationHandler",
      "org.jboss.resteasy.spi.HeaderValueProcessor",
      "org.apache.xerces.util.AugmentationsImpl$LargeContainer",
      "org.apache.xerces.impl.dtd.BalancedDTDGrammar",
      "org.apache.xerces.xni.XMLDTDHandler",
      "org.apache.xerces.impl.dtd.XML11DTDProcessor",
      "org.apache.xerces.parsers.XML11Configuration",
      "org.apache.xerces.impl.dtd.XMLDTDValidatorFilter",
      "com.att.eelf.i18n.EELFResourceManager",
      "org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate",
      "org.jboss.resteasy.core.MediaTypeMap$Typed",
      "org.openecomp.mso.logger.MessageEnum",
      "org.openecomp.mso.logger.MsoLogger$ResponseCode",
      "org.openecomp.mso.logger.MsoLogger$StatusCode",
      "com.att.eelf.configuration.EELFManager",
      "org.jboss.resteasy.spi.HttpResponse",
      "org.apache.xerces.impl.validation.EntityState",
      "org.apache.xerces.impl.XMLEntityManager$ExternalEntity",
      "org.apache.xerces.util.ParserConfigurationSettings",
      "org.apache.xerces.impl.dv.ObjectFactory$ConfigurationError",
      "com.att.eelf.i18n.EELFResourceManager$1",
      "org.apache.xerces.impl.dtd.XML11DTDValidator"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MsoLoggingServletESTestscaffolding.class.getClassLoader());

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.att.eelf.i18n.EELFResourceManager",
      "org.openecomp.mso.logger.MessageEnum",
      "org.openecomp.mso.logger.MsoLogger$Catalog",
      "org.openecomp.mso.logger.MsoLogger",
      "com.att.eelf.i18n.EELFMsgs",
      "com.att.eelf.i18n.EELFResourceManager$RESOURCE_TYPES",
      "org.apache.xerces.jaxp.SAXParserFactoryImpl",
      "org.apache.xerces.jaxp.SAXParserImpl",
      "org.apache.xerces.parsers.XMLParser",
      "org.apache.xerces.parsers.AbstractSAXParser",
      "org.apache.xerces.parsers.SAXParser",
      "org.apache.xerces.parsers.ObjectFactory",
      "org.apache.xerces.util.ParserConfigurationSettings",
      "org.apache.xerces.parsers.XML11Configuration",
      "org.apache.xerces.parsers.XIncludeAwareParserConfiguration",
      "org.apache.xerces.util.SymbolTable",
      "org.apache.xerces.impl.XMLEntityManager",
      "org.apache.xerces.util.AugmentationsImpl$SmallContainer",
      "org.apache.xerces.impl.XMLEntityManager$ByteBufferPool",
      "org.apache.xerces.impl.XMLEntityManager$CharacterBufferPool",
      "org.apache.xerces.impl.XMLEntityScanner$1",
      "org.apache.xerces.impl.XMLEntityScanner",
      "org.apache.xerces.impl.XMLErrorReporter",
      "org.apache.xerces.impl.XMLScanner",
      "org.apache.xerces.impl.XMLDocumentFragmentScannerImpl",
      "org.apache.xerces.impl.XMLDocumentScannerImpl",
      "org.apache.xerces.util.XMLStringBuffer",
      "org.apache.xerces.util.XMLAttributesImpl",
      "org.apache.xerces.impl.XMLDTDScannerImpl",
      "org.apache.xerces.impl.dtd.XMLDTDProcessor",
      "org.apache.xerces.impl.dtd.XMLDTDValidator",
      "org.apache.xerces.impl.validation.ValidationState",
      "org.apache.xerces.impl.dtd.XMLElementDecl",
      "org.apache.xerces.impl.dtd.XMLSimpleType",
      "org.apache.xerces.impl.dv.DTDDVFactory",
      "org.apache.xerces.impl.dv.ObjectFactory",
      "org.apache.xerces.impl.dv.dtd.DTDDVFactoryImpl",
      "org.apache.xerces.impl.XMLVersionDetector",
      "org.apache.xerces.impl.msg.XMLMessageFormatter",
      "org.apache.xerces.impl.io.UTF8Reader",
      "org.apache.xerces.util.XMLSymbols",
      "org.apache.xerces.xni.NamespaceContext",
      "org.apache.xerces.util.XMLChar",
      "org.apache.xerces.impl.Constants",
      "com.att.eelf.configuration.EELFLogger$Level",
      "com.att.eelf.configuration.EELFManager",
      "org.jboss.resteasy.logging.Logger$LoggerType",
      "org.jboss.resteasy.logging.Logger",
      "org.jboss.resteasy.spi.ResteasyProviderFactory",
      "org.jboss.resteasy.core.MediaTypeMap",
      "org.jboss.resteasy.core.interception.LegacyPrecedence",
      "org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate",
      "org.jboss.resteasy.plugins.delegates.NewCookieHeaderDelegate",
      "org.jboss.resteasy.specimpl.MultivaluedTreeMap",
      "org.jboss.resteasy.util.CaseInsensitiveMap$CaseInsensitiveComparator",
      "org.jboss.resteasy.util.CaseInsensitiveMap",
      "org.jboss.resteasy.core.Headers",
      "org.openecomp.mso.logger.MsoLoggingServlet"
    );
  }
}
