/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 25 13:38:39 GMT 2016
 */

package org.openecomp.mso.asdc.client.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class ArtifactInstallerExceptionESTest extends ArtifactInstallerExceptionESTestscaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ArtifactInstallerException artifactInstallerException0 = new ArtifactInstallerException("kD=Ua3[");
      ArtifactInstallerException artifactInstallerException1 = new ArtifactInstallerException("kD=Ua3[", (Throwable) artifactInstallerException0);
      assertFalse(artifactInstallerException1.equals((Object)artifactInstallerException0));
  }
}
