aai:
  auth: 757A94191D685FD2092AC1490730A4FC
  dme2:
    timeout: '30000'
  endpoint: https://aai-pwt3.ecomp.cci.att.com:8443
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    history-level: full
    license-file: file:///license.txt
    job-execution:
      max-pool-size: 30
      core-pool-size: 3
canopi:
  auth: 757A94191D685FD2092AC1490730A4FC
csi:
  aots:
    addincidentmanagement:
      endpoint: http://localhost:28090/AddIncidentManagementTicketRequest
  networkstatus:
    endpoint: http://localhost:28090/SendManagedNetworkStatusNotification
entitymanager:
  packagesToScan: com

mso:
  correlation:
    timeout: 60
  logPath: logs
  async:
    core-pool-size: 50
    max-pool-size: 50
    queue-capacity: 500
  adapters:
    completemsoprocess:
      endpoint: http://mso-ecomp.dev.att.com:30253/CompleteMsoProcess
    db:
      auth: 26AFB797A6A57960D5D718491925C50F77CDC22AC394B3DBA09950D8FD1C0764
      password: wLg4sjrAFUS8rfVfdvTXeQ==
      endpoint: http://localhost:30257/services/RequestsDbAdapter
      att-endpoint: http://localhost:30257/services/AttRequestsDbAdapter
      spring:
        endpoint: http://localhost:30257
    network:
      endpoint: http://mso-ecomp.dev.att.com:30253/services/NetworkAdapter
      rest:
        endpoint: http://mso-ecomp.dev.att.com:30253/services/rest/v1/networks
    openecomp:
      db:
        endpoint: http://mso-ecomp.dev.att.com:30257/services/RequestsDbAdapter
    po:
      auth: 757A94191D685FD2092AC1490730A4FC
      password: 3141634BF7E070AA289CF2892C986C0B
    sdnc:
      endpoint: http://mso-ecomp.dev.att.com:30254/adapters/SDNCAdapter
      rest:
        endpoint: http://mso-ecomp.dev.att.com:30254/adapters/rest/v1/sdnc
      timeout: PT60S
    tenant:
      endpoint: http://mso-ecomp.dev.att.com:30253/services/TenantAdapter
    vnf:
      endpoint: http://mso-ecomp.dev.att.com:30253/services/VnfAdapter
      rest:
        endpoint: http://mso-ecomp.dev.att.com:30253/services/rest/vnfs/v1/vnfs
    volume-groups:
      rest:
        endpoint: http://mso-ecomp.dev.att.com:30253/services/rest/v1/volume-groups
    vnf-async:
      endpoint: http://mso-ecomp.dev.att.com:30253/services/VnfAdapterAsync
  adiod:
    vce:
      service:
        model:
          invariant:
            uuid: 1cc4e2e4-eb6e-404d-a66f-c8733cedcce8
          version: '5.0'
  bpmn:
    process:
      historyTimeToLive: '30'
  callbackRetryAttempts: '5'
  catalog:
    db:
      endpoint: http://localhost:30258/ecomp/mso/catalog
      spring:
        endpoint:  http://localhost:30258
  csi:
    pwd: 4EA237303511EFBBC37F17A351562131
    sendmanagednetworkstatusnotification:
      applicationname: NetworkManagementEthernetOverFiber
      version: '212'
    usrname: mso
  db:
    auth: Basic YnBlbDptc28tZGItMTUwNyE=
  default:
    adapter:
      namespace: http://org.onap.mso
  gateway:
    service:
      model:
        name: HNGWaaS for DHV Test
  healthcheck:
    log:
      debug: 'false'
  infra:
    customer:
      id: testCustIdInfra
  msoKey: 07a7159d3bf51a0e53be7a8f89699be7
  oam:
    network:
      role:
        gateway: HngwOamNetVto.OAM
        portal: HnportalOamNetVto.OAM
  po:
    timeout: PT60S
  portal:
    service:
      model:
        name: HNPortalaaS for DHV Test
  request:
    db:
      endpoint: http://localhost:28090/
  rollback: 'true'
  sdnc:
    firewall:
      yang:
        model:
          version: '2015-05-15'
    password: 3141634BF7E070AA289CF2892C986C0B
    timeout:
      firewall:
        minutes: '20'
      ucpe:
        async:
          hours: '120'
          minutes: '5'
  service:
    agnostic:
      sniro:
        endpoint: /sniro/api/v2/placement
        host: http://mso-ecomp.dev.att.com:30253
  site-name: CamundaEngine
  sniro:
    auth: test:testpwd
    callback: http://localhost:28090/adapters/rest/SDNCNotify
    endpoint: http://localhost:28090/optimizationInstance/V1/create
    policies:
      dhv:
        2vvig: SNIRO.DistanceToLocationPolicy_vhngw,SNIRO.VNFPolicy_vhngatewayprimary1_v1,SNIRO.ResourceInstancePolicy_hngateway,SNIRO.ResourceRegionPolicy_hngateway_v1,SNIRO.VNFPolicy_vhngatewaysecondary1_v1,SNIRO.ZonePolicy_vhngw,SNIRO.PlacementOptimizationPolicy_dhv_v3,SNIRO.VNFPolicy_vhnportal_primary1_v1,SNIRO.ResourceInstancePolicy_vhnportal_v3,SNIRO.ResourceRegionPolicy_vhnportal_v1,SNIRO.VNFPolicy_vhnportalsecondary1_v1,SNIRO.ZonePolicy_vhnportal,SNIRO.DistanceToLocationPolicy_vvig,SNIRO.InventoryGroupPolicy_vvig,SNIRO.VNFPolicy_vvigprimary1_v1,SNIRO.ResourceInstancePolicy_vvig,SNIRO.VNFPolicy_vvigsecondary1_v1
        4vvig: SNIRO.DistanceToLocationPolicy_vhngw,SNIRO.VNFPolicy_vhngatewayprimary1_v1,SNIRO.ResourceInstancePolicy_hngateway,SNIRO.ResourceRegionPolicy_hngateway_v1,SNIRO.VNFPolicy_vhngatewaysecondary1_v1,SNIRO.ZonePolicy_vhngw,SNIRO.PlacementOptimizationPolicy_dhv_v3,SNIRO.VNFPolicy_vhnportal_primary1_v1,SNIRO.ResourceInstancePolicy_vhnportal_v3,SNIRO.ResourceRegionPolicy_vhnportal_v1,SNIRO.VNFPolicy_vhnportalsecondary1_v1,SNIRO.ZonePolicy_vhnportal,SNIRO.VNFPolicy_vvigprimary2_v1,SNIRO.VNFPolicy_vvigsecondary2_v1,SNIRO.DistanceToLocationPolicy_vvig,SNIRO.InventoryGroupPolicy_vvig,SNIRO.VNFPolicy_vvigprimary1_v1,SNIRO.ResourceInstancePolicy_vvig,SNIRO.VNFPolicy_vvigsecondary1_v1
    timeout: PT30M
  sriov:
    network:
      role:
        gateway1: HngwSriovProviderNet.SR_IOV_Provider2_1
        gateway2: HngwSriovProviderNet.SR_IOV_Provider2_2
        portal1: HnportalSriovProviderNet3.SR_IOV_Provider2_1
        portal2: HnportalSriovProviderNet3.SR_IOV_Provider2_2
  workflow:
    CreateGenericVNFV1:
      aai:
        volume-group:
          uri: /aai/v6/cloud-infrastructure/volume-groups/volume-group
    DHVCreateService:
      aai:
        customer:
          uri: /aai/v9/business/customers/customer
    createvce:
      delay:
        seconds: '1'
    default:
      aai:
        version: '8'
        cloud-region:
          version: '9'
        generic-vnf:
          version: '9'
        v11:
          customer:
            uri: /aai/v11/business/customers/customer
          generic-query:
            uri: /aai/v11/search/generic-query
          generic-vnf:
            uri: /aai/v11/network/generic-vnfs/generic-vnf
          l3-network:
            uri: /aai/v11/network/l3-networks/l3-network
          network-policy:
            uri: /aai/v11/network/network-policies/network-policy
          nodes-query:
            uri: /aai/v11/search/nodes-query
          route-table-reference:
            uri: /aai/v11/network/route-table-references/route-table-reference
          tenant:
            uri: /aai/v11/cloud-infrastructure/cloud-regions/cloud-region/att-aic/AAIAIC25/tenants/tenant
          vce:
            uri: /aai/v11/network/vces/vce
          vpn-binding:
            uri: /aai/v11/network/vpn-bindings/vpn-binding
        v8:
          configuration:
            uri: /aai/v11/network/configurations/configuration
          customer:
            uri: /aai/v8/business/customers/customer
          generic-query:
            uri: /aai/v8/search/generic-query
          l3-network:
            uri: /aai/v8/network/l3-networks/l3-network
          network-policy:
            uri: /aai/v8/network/network-policies/network-policy
          nodes-query:
            uri: /aai/v8/search/nodes-query
          route-table-reference:
            uri: /aai/v8/network/route-table-references/route-table-reference
          tenant:
            uri: /aai/v8/cloud-infrastructure/cloud-regions/cloud-region/att-aic/AAIAIC25/tenants/tenant
          vce:
            uri: /aai/v8/network/vces/vce
          vpn-binding:
            uri: /aai/v8/network/vpn-bindings/vpn-binding
        v9:
          cloud-region:
            uri: /aai/v9/cloud-infrastructure/cloud-regions/cloud-region/att-aic
          generic-vnf:
            uri: /aai/v9/network/generic-vnfs/generic-vnf
      retry:
        attempts: '1'
    deleteCinderVolumeV1:
      aai:
        volume-group:
          uri: /aai/v6/cloud-infrastructure/volume-groups/volume-group
    global:
      default:
        aai:
          namespace: http://org.openecomp.aai.inventory/
    l3ToHigherLayerAddBonding:
      model:
        invariantid: 50359538-066f-4a8d-807f-f2bc8eaa79dc
        name: WAN Bonding v0.1
        version: '0.1'
        versionid: 52dbec20-47aa-42e4-936c-331d8e350d44
    message:
      endpoint: http://mso-ecomp.dev.att.com:30252/mso/WorkflowMessage
    notification:
      name: GenericNotificationServiceATT
    sdncadapter:
      callback: http://mso-ecomp.dev.att.com:30254/mso/SDNCAdapterCallbackService
    vnfadapter:
      create:
        callback: http://mso-ecomp.dev.att.com:30253/mso/vnfAdapterNotify
      delete:
        callback: http://mso-ecomp.dev.att.com:30253/mso/vnfAdapterNotify
      query:
        callback: http://mso-ecomp.dev.att.com:30253/mso/vnfAdapterNotify
      rollback:
        callback: http://mso-ecomp.dev.att.com:30253/mso/vnfAdapterNotify
  global:
    dmaap:
      username: m04768@dev.mso.att.com
      password: alRyMzJ3NUNeakxl
      host: http://olsd004.wnsnet.attws.com:3904
      publisher:
        topic: org.onap.mso.dev.25239-asyncStatusUpdate-v1 
policy:
  auth: Basic dGVzdHBkcDphbHBoYTEyMw==
  client:
    auth: Basic bTAzNzQzOnBvbGljeVIwY2sk
  endpoint: https://mtanjvsgcvm02.nvp.cip.att.com:8081/pdp/api/
  environment: TEST
sdnc:
  auth: Basic YWRtaW46YWRtaW4=
  host: https://sdncodl.it.us.03.aic.cip.att.com:8443
  path: /restconf/operations/GENERIC-RESOURCE-API
sdno:
  health-check:
    dmaap:
      password: eHQ1cUJrOUc
      publisher:
        topic: org.onap.sdno.test-health-diagnostic-v02
      subscriber:
        topic: org.onap.sdno.test-health-diagnostic-v02
      username: m04768@mso.ecomp.att.com
      
appc:
  client:
    topic:
      read: 
        name: APPC-TEST-AMDOCS2
        timeout: 360000 
      write: APPC-TEST-AMDOCS1-IST
    response:
      timeout: 360000
    key: LSl8QKolmKcC0yJR
    secret: lgjXraD1HutKxv8jEN6tVouu
    service: ueb
    poolMembers: uebsb93kcdc.it.att.com:3904,uebsb92kcdc.it.att.com:3904,uebsb91kcdc.it.att.com:3904
server:
  port: 8080
  tomcat:
    max-threads: 50
  # ssl:
    # key-store: /app/msoClientKeyStore.jks
    # key-store-password: mso4you
    # key-store-type: JKS
    # trust-store: /app/msoTrustStore.jks
    # trust-store-password: mso_Domain2.0_4you
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  security:
    usercredentials:
    -  
      username: apihBpmn
      password: '$2a$12$chgDUKcdlf1t41CtS/kjIOwRuq0zWdvCcYYXtyL5TqNdPW0GhN4e6'
      role: BPMN-Client
    -  
      username: sdncaBpmn
      password: '$2a$12$1TeeS2hAXtqXgdL7f2jCWeF5on7/lrrVZqRmqUqYijOTfrlS2CZae'
      role: BPMN-Client 
    -  
      username: poBpmn
      password: '$2a$12$TixZE5fK3YkTzWcpktm.Uuk5ePFOD2n9sj2ugGRybfsz0QQ0TKLAS'
      role: BPMN-Client
    -  
      username: wmaBpmn
      password: '$2a$12$WucJSJD5iUD9MuEzhfuSmeF1W/zPMbcu.384Lh8gCkB7SPtKqZQna'
      role: BPMN-Client
    -  
      username: sniro
      password: '$2a$12$lbOQWS1iDmdQPxW2Mb6OiuTzGaPUrkrvoKVn2zwpFWb6n5Y86Lf1y'
      role: SNIRO-Client
    -  
      username: mso_admin
      password: '$2a$12$tidKuu.h88E2nuL95pTVY.ZOYMN/1dp29A9b1o.0GFDsVVSYlMkHa'
      role: ACTUATOR      	  
request:
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    intialize: true 
    
# Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: create

#Actuator
management: 
  context-path: /manage


