server: 
  port: 8080  
  tomcat:
    max-threads: 50

spring: 
  datasource:
     driver-class-name: org.mariadb.jdbc.Driver 
     url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/camundabpmn
     username: ${DB_USERNAME}
     password: ${DB_PASSWORD}
     dbcp2: 
      initial-size: 5
      max-total: 20 
      validation-query: select 1
      test-on-borrow: true 
#Actuator
management: 
  context-path: /manage
