/*-
 * ============LICENSE_START=======================================================
 * ONAP - SO
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.09.03 at 02:02:13 PM EDT
//


package org.onap.so.apihandlerinfra.vnfbeans;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vnf-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vf-module-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vnf-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vf-module-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vnf-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vf-module-model-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="asdc-service-model-version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="service-instance-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="backout-on-failure" type="{http://www.w3.org/2001/XMLSchema}Boolean"/>
 *         &lt;choice>
 *         	&lt;element name="service-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         	&lt;element name="service-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *         	&lt;element name="aic-node-clli" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *          &lt;element name="aic-cloud-region" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="tenant-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prov-status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="volume-group-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="volume-group-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="persona-model-id" type="{http://www.w3.org/2001/XMLSchema}string"/ minOccurs="0">
 *         &lt;element name="persona-model-version" type="{http://www.w3.org/2001/XMLSchema}string"/ minOccurs="0">
 *         &lt;element name="is-base-vf-module" type="{http://www.w3.org/2001/XMLSchema}Boolean"/ minOccurs="0">
 *         &lt;element name="vnf-persona-model-id" type="{http://www.w3.org/2001/XMLSchema}string"/ minOccurs="0">
 *         &lt;element name="vnf-persona-model-version" type="{http://www.w3.org/2001/XMLSchema}string"/ minOccurs="0">
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "",
        propOrder = {"vnfId", "vfModuleId", "vnfName", "vfModuleName", "vnfType", "vfModuleModelName",
                "asdcServiceModelVersion", "serviceInstanceId", "backoutOnFailure", "serviceType", "serviceId",
                "aicNodeClli", "aicCloudRegion", "tenantId", "provStatus", "volumeGroupName", "volumeGroupId",
                // BEGIN - elements valid only on BPMN interface
                "personaModelId", "personaModelVersion", "isBaseVfModule", "vnfPersonaModelId", "vnfPersonaModelVersion"
        // END - elements valid only on BPMN interface
        })
@XmlRootElement(name = "vnf-inputs")
public class VnfInputs {

    @XmlElement(name = "vnf-id")
    protected String vnfId;
    @XmlElement(name = "vf-module-id")
    protected String vfModuleId;
    @XmlElement(name = "vnf-name")
    protected String vnfName;
    @XmlElement(name = "vf-module-name")
    protected String vfModuleName;
    @XmlElement(name = "vnf-type")
    protected String vnfType;
    @XmlElement(name = "vf-module-model-name")
    protected String vfModuleModelName;
    @XmlElement(name = "asdc-service-model-version")
    protected String asdcServiceModelVersion;
    @XmlElement(name = "service-instance-id")
    protected String serviceInstanceId;
    @XmlElement(name = "backout-on-failure")
    protected Boolean backoutOnFailure;
    @XmlElement(name = "service-type")
    protected String serviceType;
    @XmlElement(name = "service-id")
    protected String serviceId;
    @XmlElement(name = "aic-node-clli")
    protected String aicNodeClli;
    @XmlElement(name = "aic-cloud-region")
    protected String aicCloudRegion;
    @XmlElement(name = "tenant-id", required = true)
    protected String tenantId;
    @XmlElement(name = "prov-status")
    protected String provStatus;
    @XmlElement(name = "volume-group-name")
    protected String volumeGroupName;
    @XmlElement(name = "volume-group-id")
    protected String volumeGroupId;
    @XmlElement(name = "persona-model-id")
    protected String personaModelId;
    @XmlElement(name = "persona-model-version")
    protected String personaModelVersion;
    @XmlElement(name = "is-base-vf-module")
    protected Boolean isBaseVfModule;
    @XmlElement(name = "vnf-persona-model-id")
    protected String vnfPersonaModelId;
    @XmlElement(name = "vnf-persona-model-version")
    protected String vnfPersonaModelVersion;

    /**
     * Gets the value of the vnfId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVnfId() {
        return vnfId;
    }

    /**
     * Sets the value of the vnfId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVnfId(String value) {
        this.vnfId = value;
    }

    /**
     * Gets the value of the vnfName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVnfName() {
        return vnfName;
    }

    /**
     * Sets the value of the vnfName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVnfName(String value) {
        this.vnfName = value;
    }

    /**
     * Gets the value of the vnfType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVnfType() {
        return vnfType;
    }

    /**
     * Sets the value of the vnfType property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVnfType(String value) {
        this.vnfType = value;
    }

    /**
     * Gets the value of the serviceInstanceId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getServiceInstanceId() {
        return serviceInstanceId;
    }

    /**
     * Sets the value of the serviceInstanceId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setServiceInstanceId(String value) {
        this.serviceInstanceId = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setServiceId(String value) {
        this.serviceId = value;
    }


    /**
     * Gets the value of the aicNodeClli property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAicNodeClli() {
        return aicNodeClli;
    }

    /**
     * Sets the value of the aicNodeClli property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAicNodeClli(String value) {
        this.aicNodeClli = value;
    }

    /**
     * Gets the value of the aicCloudRegion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAicCloudRegion() {
        return aicCloudRegion;
    }

    /**
     * Sets the value of the aicCloudRegion property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAicCloudRegion(String value) {
        this.aicCloudRegion = value;
    }

    /**
     * Gets the value of the tenantId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * Sets the value of the tenantId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTenantId(String value) {
        this.tenantId = value;
    }

    /**
     * Gets the value of the provStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProvStatus() {
        return provStatus;
    }

    /**
     * Sets the value of the provStatus property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setProvStatus(String value) {
        this.provStatus = value;
    }

    /**
     * Gets the value of the volumeGroupName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVolumeGroupName() {
        return volumeGroupName;
    }

    /**
     * Sets the value of the volumeGroupName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVolumeGroupName(String value) {
        this.volumeGroupName = value;
    }

    /**
     * Gets the value of the volumeGroupId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVolumeGroupId() {
        return volumeGroupId;
    }

    /**
     * Sets the value of the volumeGroupId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVolumeGroupId(String value) {
        this.volumeGroupId = value;
    }

    /**
     * Gets the value of the vfModuleId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVfModuleId() {
        return vfModuleId;
    }

    /**
     * Sets the value of the vfModuleId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVfModuleId(String value) {
        this.vfModuleId = value;
    }

    /**
     * Gets the value of the vfModuleName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVfModuleName() {
        return vfModuleName;
    }

    /**
     * Sets the value of the vfModuleName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVfModuleName(String value) {
        this.vfModuleName = value;
    }

    /**
     * Gets the value of the vfModuleModelName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVfModuleModelName() {
        return vfModuleModelName;
    }

    /**
     * Sets the value of the vfModuleModelName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVfModuleModelName(String value) {
        this.vfModuleModelName = value;
    }

    /**
     * Gets the value of the asdcServiceModelVersion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAsdcServiceModelVersion() {
        return asdcServiceModelVersion;
    }

    /**
     * Sets the value of the asdcServiceModelVersion property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAsdcServiceModelVersion(String value) {
        this.asdcServiceModelVersion = value;
    }

    /**
     * Gets the value of the backoutOnFailure property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getBackoutOnFailure() {
        return backoutOnFailure;
    }

    /**
     * Sets the value of the backoutOnFailure property.
     * 
     * @param value allowed object is {@link Boolean }
     * 
     */
    public void setBackoutOnFailure(Boolean value) {
        this.backoutOnFailure = value;
    }

    /**
     * Gets the value of the personaModelId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPersonaModelId() {
        return personaModelId;
    }

    /**
     * Sets the value of the personaModelId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPersonaModelId(String value) {
        this.personaModelId = value;
    }

    /**
     * Gets the value of the personaModelVersion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPersonaModelVersion() {
        return personaModelVersion;
    }

    /**
     * Sets the value of the personaModelVersion property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPersonaModelVersion(String value) {
        this.personaModelVersion = value;
    }


    /**
     * Gets the value of the isBaseVfModule property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getIsBaseVfModule() {
        return isBaseVfModule;
    }

    /**
     * Sets the value of the isBaseVfModule property.
     * 
     * @param value allowed object is {@link Boolean }
     * 
     */
    public void setIsBaseVfModule(Boolean value) {
        this.isBaseVfModule = value;
    }

    /**
     * Gets the value of the vnfPersonaModelId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVnfPersonaModelId() {
        return vnfPersonaModelId;
    }

    /**
     * Sets the value of the vnfPersonaModelId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVnfPersonaModelId(String value) {
        this.vnfPersonaModelId = value;
    }

    /**
     * Gets the value of the vnfPersonaModelVersion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVnfPersonaModelVersion() {
        return vnfPersonaModelVersion;
    }

    /**
     * Sets the value of the vnfPersonaModelVersion property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVnfPersonaModelVersion(String value) {
        this.vnfPersonaModelVersion = value;
    }


}
