/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 14 09:28:35 GMT 2016
 */

package org.openecomp.mso.adapters.vnfrest;

import org.junit.Test;
import static org.junit.Assert.*;

import org.openecomp.mso.entity.MsoRequest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class DeleteVfModuleRequestESTest extends DeleteVfModuleRequestESTestscaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      deleteVfModuleRequest0.setVnfId("5=?YJsH");
      String string0 = deleteVfModuleRequest0.getVnfId();
      assertEquals("5=?YJsH", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      deleteVfModuleRequest0.setVfModuleStackId("}VSDk5?");
      String string0 = deleteVfModuleRequest0.getVfModuleStackId();
      assertEquals("}VSDk5?", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      deleteVfModuleRequest0.setVfModuleId("Si8s(O0S8");
      String string0 = deleteVfModuleRequest0.getVfModuleId();
      assertEquals("Si8s(O0S8", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      deleteVfModuleRequest0.setTenantId("");
      String string0 = deleteVfModuleRequest0.getTenantId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      deleteVfModuleRequest0.setMsoRequest((MsoRequest) null);
      MsoRequest msoRequest0 = deleteVfModuleRequest0.getMsoRequest();
      assertNull(msoRequest0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      deleteVfModuleRequest0.setCloudSiteId("");
      String string0 = deleteVfModuleRequest0.getCloudSiteId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      String string0 = deleteVfModuleRequest0.getVfModuleId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      String string0 = deleteVfModuleRequest0.getCloudSiteId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      deleteVfModuleRequest0.setTenantId("[!?QZiHc2[");
      String string0 = deleteVfModuleRequest0.getTenantId();
      assertEquals("[!?QZiHc2[", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      deleteVfModuleRequest0.setVnfId("");
      String string0 = deleteVfModuleRequest0.getVnfId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      deleteVfModuleRequest0.setCloudSiteId("jaxb.formatted.output");
      String string0 = deleteVfModuleRequest0.getCloudSiteId();
      assertEquals("jaxb.formatted.output", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      String string0 = deleteVfModuleRequest0.getTenantId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      String string0 = deleteVfModuleRequest0.getVnfId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      deleteVfModuleRequest0.setVfModuleId("");
      String string0 = deleteVfModuleRequest0.getVfModuleId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      deleteVfModuleRequest0.setVfModuleStackId("");
      String string0 = deleteVfModuleRequest0.getVfModuleStackId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      MsoRequest msoRequest0 = deleteVfModuleRequest0.getMsoRequest();
      deleteVfModuleRequest0.setMsoRequest(msoRequest0);
      assertNull(deleteVfModuleRequest0.getVnfId());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DeleteVfModuleRequest deleteVfModuleRequest0 = new DeleteVfModuleRequest();
      String string0 = deleteVfModuleRequest0.getVfModuleStackId();
      assertNull(string0);
  }
}
