/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 20 14:10:13 GMT 2017
 */

package org.openecomp.mso.adapters.sdncrest;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true)
public class RequestInformationESTest extends RequestInformationESTestscaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      RequestInformation requestInformation0 = new RequestInformation();
      String string0 = requestInformation0.getSource();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      RequestInformation requestInformation0 = new RequestInformation("", "", "");
      String string0 = requestInformation0.getSource();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      RequestInformation requestInformation0 = new RequestInformation();
      String string0 = requestInformation0.getRequestId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      RequestInformation requestInformation0 = new RequestInformation("82W?GC", "", "82W?GC");
      String string0 = requestInformation0.getNotificationUrl();
      assertEquals("82W?GC", string0);
      assertEquals("82W?GC", requestInformation0.getRequestId());
      assertEquals("", requestInformation0.getSource());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      RequestInformation requestInformation0 = new RequestInformation("", "3*5=IrA", "");
      String string0 = requestInformation0.getSource();
      assertEquals("3*5=IrA", string0);
      assertEquals("", requestInformation0.getNotificationUrl());
      assertEquals("", requestInformation0.getRequestId());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      RequestInformation requestInformation0 = new RequestInformation("", "3*5=IrA", "");
      assertEquals("", requestInformation0.getRequestId());

      requestInformation0.setRequestId("3*5=IrA");
      requestInformation0.getRequestId();
      assertEquals("3*5=IrA", requestInformation0.getSource());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      RequestInformation requestInformation0 = new RequestInformation();
      String string0 = requestInformation0.getNotificationUrl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      RequestInformation requestInformation0 = new RequestInformation("", "3*5=IrA", "");
      assertEquals("", requestInformation0.getNotificationUrl());

      requestInformation0.setNotificationUrl("3*5=IrA");
      assertEquals("3*5=IrA", requestInformation0.getSource());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      RequestInformation requestInformation0 = new RequestInformation("", "3*5=IrA", "");
      String string0 = requestInformation0.getNotificationUrl();
      assertEquals("", string0);
      assertEquals("", requestInformation0.getRequestId());
      assertEquals("3*5=IrA", requestInformation0.getSource());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      RequestInformation requestInformation0 = new RequestInformation("", "3*5=IrA", "");
      String string0 = requestInformation0.getRequestId();
      assertEquals("", string0);
      assertEquals("", requestInformation0.getNotificationUrl());
      assertEquals("3*5=IrA", requestInformation0.getSource());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      RequestInformation requestInformation0 = new RequestInformation("", "3*5=IrA", "");
      assertEquals("3*5=IrA", requestInformation0.getSource());

      requestInformation0.setSource("");
      assertEquals("", requestInformation0.getNotificationUrl());
  }
}
